// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct CreateChannelModeratorInputBody: Equatable {
    public let channelModeratorArn: String?
}

extension CreateChannelModeratorInputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case channelModeratorArn = "ChannelModeratorArn"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let channelModeratorArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .channelModeratorArn)
        channelModeratorArn = channelModeratorArnDecoded
    }
}
