// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetBotOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetBotOutput(bot: \(String(describing: bot)))"}
}
