// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ResolveCaseOutput: HttpResponseBinding {
    public init (httpResponse: HttpResponse, decoder: ResponseDecoder? = nil) throws {
        if case .data(let data) = httpResponse.body,
            let unwrappedData = data,
            let responseDecoder = decoder {
            let output: ResolveCaseOutputBody = try responseDecoder.decode(responseBody: unwrappedData)
            self.finalCaseStatus = output.finalCaseStatus
            self.initialCaseStatus = output.initialCaseStatus
        } else {
            self.finalCaseStatus = nil
            self.initialCaseStatus = nil
        }
    }
}
