// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct DescribeConnectionLoaInputHeadersMiddleware: Middleware {
    public let id: String = "DescribeConnectionLoaInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeConnectionLoaInput>,
                  next: H) -> Swift.Result<OperationOutput<DescribeConnectionLoaOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeConnectionLoaInput>
    public typealias MOutput = OperationOutput<DescribeConnectionLoaOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<DescribeConnectionLoaOutputError>
}

public struct DescribeConnectionLoaInputQueryItemMiddleware: Middleware {
    public let id: String = "DescribeConnectionLoaInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeConnectionLoaInput>,
                  next: H) -> Swift.Result<OperationOutput<DescribeConnectionLoaOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeConnectionLoaInput>
    public typealias MOutput = OperationOutput<DescribeConnectionLoaOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<DescribeConnectionLoaOutputError>
}

public struct DescribeConnectionLoaInputBodyMiddleware: Middleware {
    public let id: String = "DescribeConnectionLoaInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<DescribeConnectionLoaInput>,
                  next: H) -> Swift.Result<OperationOutput<DescribeConnectionLoaOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            if try !input.operationInput.allPropertiesAreNull() {
                let encoder = context.getEncoder()
                let data = try encoder.encode(input.operationInput)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            }
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<DescribeConnectionLoaInput>
    public typealias MOutput = OperationOutput<DescribeConnectionLoaOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<DescribeConnectionLoaOutputError>
}

extension DescribeConnectionLoaInput: Encodable, Reflection {
    enum CodingKeys: String, CodingKey {
        case connectionId
        case loaContentType
        case providerName
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let connectionId = connectionId {
            try encodeContainer.encode(connectionId, forKey: .connectionId)
        }
        if let loaContentType = loaContentType {
            try encodeContainer.encode(loaContentType.rawValue, forKey: .loaContentType)
        }
        if let providerName = providerName {
            try encodeContainer.encode(providerName, forKey: .providerName)
        }
    }
}
