// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UpdateQuerySuggestionsConfigInputBodyMiddleware: Middleware {
    public let id: String = "UpdateQuerySuggestionsConfigInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<UpdateQuerySuggestionsConfigInput>,
                  next: H) -> Swift.Result<OperationOutput<UpdateQuerySuggestionsConfigOutput>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            if try !input.operationInput.allPropertiesAreNull() {
                let encoder = context.getEncoder()
                let data = try encoder.encode(input.operationInput)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            }
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<UpdateQuerySuggestionsConfigInput>
    public typealias MOutput = OperationOutput<UpdateQuerySuggestionsConfigOutput>
    public typealias Context = HttpContext
    public typealias MError = SdkError<UpdateQuerySuggestionsConfigOutputError>
}
