name: 'Checkout smithy-swift composite action'
description: 'A composite action that sets up smithy-swift for the workflow.'
inputs:
  AUTOMATION_USER_SSH_PRIVATE_KEY:
    description: 'SSH private key for the automation user'
    required: true
  STAGING_PARTNER_REPO:
    description: 'The staging partner repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up SSH key
      if: ${{ github.repository != 'awslabs/aws-sdk-swift' }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.AUTOMATION_USER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash
    - name: Select staging smithy-swift branch
      if: ${{ github.repository != 'awslabs/aws-sdk-swift' }}
      run: |
        cd aws-sdk-swift
        ORIGINAL_REPO_HEAD_REF="$GITHUB_HEAD_REF" \
        DEPENDENCY_REPO_URL="git@github.com:${{ inputs.STAGING_PARTNER_REPO }}.git" \
        ./scripts/ci_steps/select_dependency_branch.sh
      shell: bash
    - name: Checkout staging smithy-swift
      if: ${{ github.repository != 'awslabs/aws-sdk-swift' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.STAGING_PARTNER_REPO }}
        ref: ${{ env.DEPENDENCY_REPO_SHA }}
        path: smithy-swift
        ssh-key: ${{ inputs.AUTOMATION_USER_SSH_PRIVATE_KEY }}
    - name: Select smithy-swift branch
      if: ${{ github.repository == 'awslabs/aws-sdk-swift' }}
      run: |
        cd aws-sdk-swift
        ORIGINAL_REPO_HEAD_REF="$GITHUB_HEAD_REF" \
        DEPENDENCY_REPO_URL="https://github.com/smithy-lang/smithy-swift.git" \
        ./scripts/ci_steps/select_dependency_branch.sh
      shell: bash
    - name: Checkout smithy-swift
      if: ${{ github.repository == 'awslabs/aws-sdk-swift' }}
      uses: actions/checkout@v4
      with:
        repository: smithy-lang/smithy-swift
        ref: ${{ env.DEPENDENCY_REPO_SHA }}
        path: smithy-swift