// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// <p>The FinSpace management service provides the APIs for managing the FinSpace
///            environments. </p>
public protocol FinspaceClientProtocol {
    /// <p>Create a new FinSpace environment.</p>
    func createEnvironment(input: CreateEnvironmentInput, completion: @escaping (SdkResult<CreateEnvironmentOutput, CreateEnvironmentOutputError>) -> Void)
    /// <p>Delete an FinSpace environment.</p>
    func deleteEnvironment(input: DeleteEnvironmentInput, completion: @escaping (SdkResult<DeleteEnvironmentOutput, DeleteEnvironmentOutputError>) -> Void)
    /// <p>Returns the FinSpace environment object.</p>
    func getEnvironment(input: GetEnvironmentInput, completion: @escaping (SdkResult<GetEnvironmentOutput, GetEnvironmentOutputError>) -> Void)
    /// <p>A list of all of your FinSpace environments.</p>
    func listEnvironments(input: ListEnvironmentsInput, completion: @escaping (SdkResult<ListEnvironmentsOutput, ListEnvironmentsOutputError>) -> Void)
    /// <p>A list of all tags for a resource.</p>
    func listTagsForResource(input: ListTagsForResourceInput, completion: @escaping (SdkResult<ListTagsForResourceOutput, ListTagsForResourceOutputError>) -> Void)
    /// <p>Adds metadata tags to a FinSpace resource.</p>
    func tagResource(input: TagResourceInput, completion: @escaping (SdkResult<TagResourceOutput, TagResourceOutputError>) -> Void)
    /// <p>Removes metadata tags from a FinSpace resource.</p>
    func untagResource(input: UntagResourceInput, completion: @escaping (SdkResult<UntagResourceOutput, UntagResourceOutputError>) -> Void)
    /// <p>Update your FinSpace environment.</p>
    func updateEnvironment(input: UpdateEnvironmentInput, completion: @escaping (SdkResult<UpdateEnvironmentOutput, UpdateEnvironmentOutputError>) -> Void)
}
