// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct CreateUploadOutputBody: Equatable {
    public let upload: Upload?
}

extension CreateUploadOutputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case upload
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let uploadDecoded = try containerValues.decodeIfPresent(Upload.self, forKey: .upload)
        upload = uploadDecoded
    }
}
