// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OfferingStatus: CustomDebugStringConvertible {
    public var debugDescription: String {
        "OfferingStatus(effectiveOn: \(String(describing: effectiveOn)), offering: \(String(describing: offering)), quantity: \(String(describing: quantity)), type: \(String(describing: type)))"}
}
