// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension AcceptEulasOutput: HttpResponseBinding {
    public init (httpResponse: HttpResponse, decoder: ResponseDecoder? = nil) throws {
        if case .data(let data) = httpResponse.body,
            let unwrappedData = data,
            let responseDecoder = decoder {
            let output: AcceptEulasOutputBody = try responseDecoder.decode(responseBody: unwrappedData)
            self.eulaAcceptances = output.eulaAcceptances
        } else {
            self.eulaAcceptances = nil
        }
    }
}
