// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetTraceGraphOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetTraceGraphOutput(nextToken: \(String(describing: nextToken)), services: \(String(describing: services)))"}
}
