// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DeleteRegexPatternSetInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DeleteRegexPatternSetInput(id: \(String(describing: id)), lockToken: \(String(describing: lockToken)), name: \(String(describing: name)), scope: \(String(describing: scope)))"}
}
