// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct SendSerialConsoleSSHPublicKeyOutput: Equatable {
    /// <p>The ID of the request. Please provide this ID when contacting AWS Support for assistance.</p>
    public let requestId: String?
    /// <p>Is true if the request succeeds and an error otherwise.</p>
    public let success: Bool

    public init (
        requestId: String? = nil,
        success: Bool = false
    )
    {
        self.requestId = requestId
        self.success = success
    }
}
