// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetThreatIntelSetOutputResponse: Equatable {
    /// <p>The format of the threatIntelSet.</p>
    public let format: ThreatIntelSetFormat?
    /// <p>The URI of the file that contains the ThreatIntelSet. For example:
    ///       https://s3.us-west-2.amazonaws.com/my-bucket/my-object-key.</p>
    public let location: String?
    /// <p>A user-friendly ThreatIntelSet name displayed in all findings that are generated by
    ///       activity that involves IP addresses included in this ThreatIntelSet.</p>
    public let name: String?
    /// <p>The status of threatIntelSet file uploaded.</p>
    public let status: ThreatIntelSetStatus?
    /// <p>The tags of the threat list resource.</p>
    public let tags: [String:String]?

    public init (
        format: ThreatIntelSetFormat? = nil,
        location: String? = nil,
        name: String? = nil,
        status: ThreatIntelSetStatus? = nil,
        tags: [String:String]? = nil
    )
    {
        self.format = format
        self.location = location
        self.name = name
        self.status = status
        self.tags = tags
    }
}

extension GetThreatIntelSetOutputResponse: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetThreatIntelSetOutputResponse(format: \(String(describing: format)), location: \(String(describing: location)), name: \(String(describing: name)), status: \(String(describing: status)), tags: \(String(describing: tags)))"}
}
