// swift-tools-version:5.5
import PackageDescription
import class Foundation.FileManager
let package = Package(
    name: "AWSSwiftSDK",
    platforms: [
        .macOS(.v10_15),
        .iOS(.v13)
    ],
    products: [
        .library(name: "AWSClientRuntime", targets: ["AWSClientRuntime"]),
        .library(name: "AWSACM", targets: ["AWSACM"]),
        .library(name: "AWSACMPCA", targets: ["AWSACMPCA"]),
        .library(name: "AWSAPIGateway", targets: ["AWSAPIGateway"]),
        .library(name: "AWSAccessAnalyzer", targets: ["AWSAccessAnalyzer"]),
        .library(name: "AWSAccount", targets: ["AWSAccount"]),
        .library(name: "AWSAlexaForBusiness", targets: ["AWSAlexaForBusiness"]),
        .library(name: "AWSAmp", targets: ["AWSAmp"]),
        .library(name: "AWSAmplify", targets: ["AWSAmplify"]),
        .library(name: "AWSAmplifyBackend", targets: ["AWSAmplifyBackend"]),
        .library(name: "AWSAmplifyUIBuilder", targets: ["AWSAmplifyUIBuilder"]),
        .library(name: "AWSApiGatewayManagementApi", targets: ["AWSApiGatewayManagementApi"]),
        .library(name: "AWSApiGatewayV2", targets: ["AWSApiGatewayV2"]),
        .library(name: "AWSAppConfig", targets: ["AWSAppConfig"]),
        .library(name: "AWSAppConfigData", targets: ["AWSAppConfigData"]),
        .library(name: "AWSAppIntegrations", targets: ["AWSAppIntegrations"]),
        .library(name: "AWSAppMesh", targets: ["AWSAppMesh"]),
        .library(name: "AWSAppRunner", targets: ["AWSAppRunner"]),
        .library(name: "AWSAppStream", targets: ["AWSAppStream"]),
        .library(name: "AWSAppSync", targets: ["AWSAppSync"]),
        .library(name: "AWSAppflow", targets: ["AWSAppflow"]),
        .library(name: "AWSApplicationAutoScaling", targets: ["AWSApplicationAutoScaling"]),
        .library(name: "AWSApplicationCostProfiler", targets: ["AWSApplicationCostProfiler"]),
        .library(name: "AWSApplicationDiscoveryService", targets: ["AWSApplicationDiscoveryService"]),
        .library(name: "AWSApplicationInsights", targets: ["AWSApplicationInsights"]),
        .library(name: "AWSAthena", targets: ["AWSAthena"]),
        .library(name: "AWSAuditManager", targets: ["AWSAuditManager"]),
        .library(name: "AWSAutoScaling", targets: ["AWSAutoScaling"]),
        .library(name: "AWSAutoScalingPlans", targets: ["AWSAutoScalingPlans"]),
        .library(name: "AWSBackup", targets: ["AWSBackup"]),
        .library(name: "AWSBackupGateway", targets: ["AWSBackupGateway"]),
        .library(name: "AWSBackupStorage", targets: ["AWSBackupStorage"]),
        .library(name: "AWSBatch", targets: ["AWSBatch"]),
        .library(name: "AWSBillingconductor", targets: ["AWSBillingconductor"]),
        .library(name: "AWSBraket", targets: ["AWSBraket"]),
        .library(name: "AWSBudgets", targets: ["AWSBudgets"]),
        .library(name: "AWSChime", targets: ["AWSChime"]),
        .library(name: "AWSChimeSDKIdentity", targets: ["AWSChimeSDKIdentity"]),
        .library(name: "AWSChimeSDKMediaPipelines", targets: ["AWSChimeSDKMediaPipelines"]),
        .library(name: "AWSChimeSDKMeetings", targets: ["AWSChimeSDKMeetings"]),
        .library(name: "AWSChimeSDKMessaging", targets: ["AWSChimeSDKMessaging"]),
        .library(name: "AWSCloud9", targets: ["AWSCloud9"]),
        .library(name: "AWSCloudControl", targets: ["AWSCloudControl"]),
        .library(name: "AWSCloudDirectory", targets: ["AWSCloudDirectory"]),
        .library(name: "AWSCloudFormation", targets: ["AWSCloudFormation"]),
        .library(name: "AWSCloudFront", targets: ["AWSCloudFront"]),
        .library(name: "AWSCloudHSM", targets: ["AWSCloudHSM"]),
        .library(name: "AWSCloudHSMV2", targets: ["AWSCloudHSMV2"]),
        .library(name: "AWSCloudSearch", targets: ["AWSCloudSearch"]),
        .library(name: "AWSCloudSearchDomain", targets: ["AWSCloudSearchDomain"]),
        .library(name: "AWSCloudTrail", targets: ["AWSCloudTrail"]),
        .library(name: "AWSCloudWatch", targets: ["AWSCloudWatch"]),
        .library(name: "AWSCloudWatchEvents", targets: ["AWSCloudWatchEvents"]),
        .library(name: "AWSCloudWatchLogs", targets: ["AWSCloudWatchLogs"]),
        .library(name: "AWSCodeBuild", targets: ["AWSCodeBuild"]),
        .library(name: "AWSCodeCommit", targets: ["AWSCodeCommit"]),
        .library(name: "AWSCodeDeploy", targets: ["AWSCodeDeploy"]),
        .library(name: "AWSCodeGuruProfiler", targets: ["AWSCodeGuruProfiler"]),
        .library(name: "AWSCodeGuruReviewer", targets: ["AWSCodeGuruReviewer"]),
        .library(name: "AWSCodePipeline", targets: ["AWSCodePipeline"]),
        .library(name: "AWSCodeStar", targets: ["AWSCodeStar"]),
        .library(name: "AWSCodeStarconnections", targets: ["AWSCodeStarconnections"]),
        .library(name: "AWSCodeartifact", targets: ["AWSCodeartifact"]),
        .library(name: "AWSCodestarnotifications", targets: ["AWSCodestarnotifications"]),
        .library(name: "AWSCognitoIdentity", targets: ["AWSCognitoIdentity"]),
        .library(name: "AWSCognitoIdentityProvider", targets: ["AWSCognitoIdentityProvider"]),
        .library(name: "AWSCognitoSync", targets: ["AWSCognitoSync"]),
        .library(name: "AWSComprehend", targets: ["AWSComprehend"]),
        .library(name: "AWSComprehendMedical", targets: ["AWSComprehendMedical"]),
        .library(name: "AWSComputeOptimizer", targets: ["AWSComputeOptimizer"]),
        .library(name: "AWSConfigService", targets: ["AWSConfigService"]),
        .library(name: "AWSConnect", targets: ["AWSConnect"]),
        .library(name: "AWSConnectCampaigns", targets: ["AWSConnectCampaigns"]),
        .library(name: "AWSConnectContactLens", targets: ["AWSConnectContactLens"]),
        .library(name: "AWSConnectParticipant", targets: ["AWSConnectParticipant"]),
        .library(name: "AWSControlTower", targets: ["AWSControlTower"]),
        .library(name: "AWSCostExplorer", targets: ["AWSCostExplorer"]),
        .library(name: "AWSCostandUsageReportService", targets: ["AWSCostandUsageReportService"]),
        .library(name: "AWSCustomerProfiles", targets: ["AWSCustomerProfiles"]),
        .library(name: "AWSDAX", targets: ["AWSDAX"]),
        .library(name: "AWSDLM", targets: ["AWSDLM"]),
        .library(name: "AWSDataBrew", targets: ["AWSDataBrew"]),
        .library(name: "AWSDataExchange", targets: ["AWSDataExchange"]),
        .library(name: "AWSDataPipeline", targets: ["AWSDataPipeline"]),
        .library(name: "AWSDataSync", targets: ["AWSDataSync"]),
        .library(name: "AWSDatabaseMigrationService", targets: ["AWSDatabaseMigrationService"]),
        .library(name: "AWSDetective", targets: ["AWSDetective"]),
        .library(name: "AWSDevOpsGuru", targets: ["AWSDevOpsGuru"]),
        .library(name: "AWSDeviceFarm", targets: ["AWSDeviceFarm"]),
        .library(name: "AWSDirectConnect", targets: ["AWSDirectConnect"]),
        .library(name: "AWSDirectoryService", targets: ["AWSDirectoryService"]),
        .library(name: "AWSDocDB", targets: ["AWSDocDB"]),
        .library(name: "AWSDrs", targets: ["AWSDrs"]),
        .library(name: "AWSDynamoDB", targets: ["AWSDynamoDB"]),
        .library(name: "AWSDynamoDBStreams", targets: ["AWSDynamoDBStreams"]),
        .library(name: "AWSEBS", targets: ["AWSEBS"]),
        .library(name: "AWSEC2", targets: ["AWSEC2"]),
        .library(name: "AWSEC2InstanceConnect", targets: ["AWSEC2InstanceConnect"]),
        .library(name: "AWSECR", targets: ["AWSECR"]),
        .library(name: "AWSECRPUBLIC", targets: ["AWSECRPUBLIC"]),
        .library(name: "AWSECS", targets: ["AWSECS"]),
        .library(name: "AWSEFS", targets: ["AWSEFS"]),
        .library(name: "AWSEKS", targets: ["AWSEKS"]),
        .library(name: "AWSEMR", targets: ["AWSEMR"]),
        .library(name: "AWSEMRServerless", targets: ["AWSEMRServerless"]),
        .library(name: "AWSEMRcontainers", targets: ["AWSEMRcontainers"]),
        .library(name: "AWSElastiCache", targets: ["AWSElastiCache"]),
        .library(name: "AWSElasticBeanstalk", targets: ["AWSElasticBeanstalk"]),
        .library(name: "AWSElasticInference", targets: ["AWSElasticInference"]),
        .library(name: "AWSElasticLoadBalancing", targets: ["AWSElasticLoadBalancing"]),
        .library(name: "AWSElasticLoadBalancingv2", targets: ["AWSElasticLoadBalancingv2"]),
        .library(name: "AWSElasticTranscoder", targets: ["AWSElasticTranscoder"]),
        .library(name: "AWSElasticsearchService", targets: ["AWSElasticsearchService"]),
        .library(name: "AWSEventBridge", targets: ["AWSEventBridge"]),
        .library(name: "AWSEvidently", targets: ["AWSEvidently"]),
        .library(name: "AWSFMS", targets: ["AWSFMS"]),
        .library(name: "AWSFSx", targets: ["AWSFSx"]),
        .library(name: "AWSFinspace", targets: ["AWSFinspace"]),
        .library(name: "AWSFinspacedata", targets: ["AWSFinspacedata"]),
        .library(name: "AWSFirehose", targets: ["AWSFirehose"]),
        .library(name: "AWSFis", targets: ["AWSFis"]),
        .library(name: "AWSForecast", targets: ["AWSForecast"]),
        .library(name: "AWSForecastquery", targets: ["AWSForecastquery"]),
        .library(name: "AWSFraudDetector", targets: ["AWSFraudDetector"]),
        .library(name: "AWSGameLift", targets: ["AWSGameLift"]),
        .library(name: "AWSGameSparks", targets: ["AWSGameSparks"]),
        .library(name: "AWSGlacier", targets: ["AWSGlacier"]),
        .library(name: "AWSGlobalAccelerator", targets: ["AWSGlobalAccelerator"]),
        .library(name: "AWSGlue", targets: ["AWSGlue"]),
        .library(name: "AWSGrafana", targets: ["AWSGrafana"]),
        .library(name: "AWSGreengrass", targets: ["AWSGreengrass"]),
        .library(name: "AWSGreengrassV2", targets: ["AWSGreengrassV2"]),
        .library(name: "AWSGroundStation", targets: ["AWSGroundStation"]),
        .library(name: "AWSGuardDuty", targets: ["AWSGuardDuty"]),
        .library(name: "AWSHealth", targets: ["AWSHealth"]),
        .library(name: "AWSHealthLake", targets: ["AWSHealthLake"]),
        .library(name: "AWSHoneycode", targets: ["AWSHoneycode"]),
        .library(name: "AWSIAM", targets: ["AWSIAM"]),
        .library(name: "AWSIdentitystore", targets: ["AWSIdentitystore"]),
        .library(name: "AWSImagebuilder", targets: ["AWSImagebuilder"]),
        .library(name: "AWSInspector", targets: ["AWSInspector"]),
        .library(name: "AWSInspector2", targets: ["AWSInspector2"]),
        .library(name: "AWSIoT", targets: ["AWSIoT"]),
        .library(name: "AWSIoT1ClickDevicesService", targets: ["AWSIoT1ClickDevicesService"]),
        .library(name: "AWSIoT1ClickProjects", targets: ["AWSIoT1ClickProjects"]),
        .library(name: "AWSIoTAnalytics", targets: ["AWSIoTAnalytics"]),
        .library(name: "AWSIoTDataPlane", targets: ["AWSIoTDataPlane"]),
        .library(name: "AWSIoTEvents", targets: ["AWSIoTEvents"]),
        .library(name: "AWSIoTEventsData", targets: ["AWSIoTEventsData"]),
        .library(name: "AWSIoTFleetHub", targets: ["AWSIoTFleetHub"]),
        .library(name: "AWSIoTFleetWise", targets: ["AWSIoTFleetWise"]),
        .library(name: "AWSIoTJobsDataPlane", targets: ["AWSIoTJobsDataPlane"]),
        .library(name: "AWSIoTSecureTunneling", targets: ["AWSIoTSecureTunneling"]),
        .library(name: "AWSIoTSiteWise", targets: ["AWSIoTSiteWise"]),
        .library(name: "AWSIoTThingsGraph", targets: ["AWSIoTThingsGraph"]),
        .library(name: "AWSIoTTwinMaker", targets: ["AWSIoTTwinMaker"]),
        .library(name: "AWSIoTWireless", targets: ["AWSIoTWireless"]),
        .library(name: "AWSIotDeviceAdvisor", targets: ["AWSIotDeviceAdvisor"]),
        .library(name: "AWSIvs", targets: ["AWSIvs"]),
        .library(name: "AWSIvschat", targets: ["AWSIvschat"]),
        .library(name: "AWSKMS", targets: ["AWSKMS"]),
        .library(name: "AWSKafka", targets: ["AWSKafka"]),
        .library(name: "AWSKafkaConnect", targets: ["AWSKafkaConnect"]),
        .library(name: "AWSKendra", targets: ["AWSKendra"]),
        .library(name: "AWSKeyspaces", targets: ["AWSKeyspaces"]),
        .library(name: "AWSKinesis", targets: ["AWSKinesis"]),
        .library(name: "AWSKinesisAnalytics", targets: ["AWSKinesisAnalytics"]),
        .library(name: "AWSKinesisAnalyticsV2", targets: ["AWSKinesisAnalyticsV2"]),
        .library(name: "AWSKinesisVideo", targets: ["AWSKinesisVideo"]),
        .library(name: "AWSKinesisVideoArchivedMedia", targets: ["AWSKinesisVideoArchivedMedia"]),
        .library(name: "AWSKinesisVideoMedia", targets: ["AWSKinesisVideoMedia"]),
        .library(name: "AWSKinesisVideoSignaling", targets: ["AWSKinesisVideoSignaling"]),
        .library(name: "AWSLakeFormation", targets: ["AWSLakeFormation"]),
        .library(name: "AWSLambda", targets: ["AWSLambda"]),
        .library(name: "AWSLexModelBuildingService", targets: ["AWSLexModelBuildingService"]),
        .library(name: "AWSLexModelsV2", targets: ["AWSLexModelsV2"]),
        .library(name: "AWSLexRuntimeService", targets: ["AWSLexRuntimeService"]),
        .library(name: "AWSLexRuntimeV2", targets: ["AWSLexRuntimeV2"]),
        .library(name: "AWSLicenseManager", targets: ["AWSLicenseManager"]),
        .library(name: "AWSLicenseManagerUserSubscriptions", targets: ["AWSLicenseManagerUserSubscriptions"]),
        .library(name: "AWSLightsail", targets: ["AWSLightsail"]),
        .library(name: "AWSLocation", targets: ["AWSLocation"]),
        .library(name: "AWSLookoutEquipment", targets: ["AWSLookoutEquipment"]),
        .library(name: "AWSLookoutMetrics", targets: ["AWSLookoutMetrics"]),
        .library(name: "AWSLookoutVision", targets: ["AWSLookoutVision"]),
        .library(name: "AWSM2", targets: ["AWSM2"]),
        .library(name: "AWSMTurk", targets: ["AWSMTurk"]),
        .library(name: "AWSMWAA", targets: ["AWSMWAA"]),
        .library(name: "AWSMachineLearning", targets: ["AWSMachineLearning"]),
        .library(name: "AWSMacie", targets: ["AWSMacie"]),
        .library(name: "AWSMacie2", targets: ["AWSMacie2"]),
        .library(name: "AWSManagedBlockchain", targets: ["AWSManagedBlockchain"]),
        .library(name: "AWSMarketplaceCatalog", targets: ["AWSMarketplaceCatalog"]),
        .library(name: "AWSMarketplaceCommerceAnalytics", targets: ["AWSMarketplaceCommerceAnalytics"]),
        .library(name: "AWSMarketplaceEntitlementService", targets: ["AWSMarketplaceEntitlementService"]),
        .library(name: "AWSMarketplaceMetering", targets: ["AWSMarketplaceMetering"]),
        .library(name: "AWSMediaConnect", targets: ["AWSMediaConnect"]),
        .library(name: "AWSMediaConvert", targets: ["AWSMediaConvert"]),
        .library(name: "AWSMediaLive", targets: ["AWSMediaLive"]),
        .library(name: "AWSMediaPackage", targets: ["AWSMediaPackage"]),
        .library(name: "AWSMediaPackageVod", targets: ["AWSMediaPackageVod"]),
        .library(name: "AWSMediaStore", targets: ["AWSMediaStore"]),
        .library(name: "AWSMediaStoreData", targets: ["AWSMediaStoreData"]),
        .library(name: "AWSMediaTailor", targets: ["AWSMediaTailor"]),
        .library(name: "AWSMemoryDB", targets: ["AWSMemoryDB"]),
        .library(name: "AWSMgn", targets: ["AWSMgn"]),
        .library(name: "AWSMigrationHub", targets: ["AWSMigrationHub"]),
        .library(name: "AWSMigrationHubConfig", targets: ["AWSMigrationHubConfig"]),
        .library(name: "AWSMigrationHubOrchestrator", targets: ["AWSMigrationHubOrchestrator"]),
        .library(name: "AWSMigrationHubRefactorSpaces", targets: ["AWSMigrationHubRefactorSpaces"]),
        .library(name: "AWSMigrationHubStrategy", targets: ["AWSMigrationHubStrategy"]),
        .library(name: "AWSMobile", targets: ["AWSMobile"]),
        .library(name: "AWSMq", targets: ["AWSMq"]),
        .library(name: "AWSNeptune", targets: ["AWSNeptune"]),
        .library(name: "AWSNetworkFirewall", targets: ["AWSNetworkFirewall"]),
        .library(name: "AWSNetworkManager", targets: ["AWSNetworkManager"]),
        .library(name: "AWSNimble", targets: ["AWSNimble"]),
        .library(name: "AWSOpenSearch", targets: ["AWSOpenSearch"]),
        .library(name: "AWSOpsWorks", targets: ["AWSOpsWorks"]),
        .library(name: "AWSOpsWorksCM", targets: ["AWSOpsWorksCM"]),
        .library(name: "AWSOrganizations", targets: ["AWSOrganizations"]),
        .library(name: "AWSOutposts", targets: ["AWSOutposts"]),
        .library(name: "AWSPI", targets: ["AWSPI"]),
        .library(name: "AWSPanorama", targets: ["AWSPanorama"]),
        .library(name: "AWSPersonalize", targets: ["AWSPersonalize"]),
        .library(name: "AWSPersonalizeEvents", targets: ["AWSPersonalizeEvents"]),
        .library(name: "AWSPersonalizeRuntime", targets: ["AWSPersonalizeRuntime"]),
        .library(name: "AWSPinpoint", targets: ["AWSPinpoint"]),
        .library(name: "AWSPinpointEmail", targets: ["AWSPinpointEmail"]),
        .library(name: "AWSPinpointSMSVoice", targets: ["AWSPinpointSMSVoice"]),
        .library(name: "AWSPinpointSMSVoiceV2", targets: ["AWSPinpointSMSVoiceV2"]),
        .library(name: "AWSPolly", targets: ["AWSPolly"]),
        .library(name: "AWSPricing", targets: ["AWSPricing"]),
        .library(name: "AWSPrivateNetworks", targets: ["AWSPrivateNetworks"]),
        .library(name: "AWSProton", targets: ["AWSProton"]),
        .library(name: "AWSQLDB", targets: ["AWSQLDB"]),
        .library(name: "AWSQLDBSession", targets: ["AWSQLDBSession"]),
        .library(name: "AWSQuickSight", targets: ["AWSQuickSight"]),
        .library(name: "AWSRAM", targets: ["AWSRAM"]),
        .library(name: "AWSRDS", targets: ["AWSRDS"]),
        .library(name: "AWSRDSData", targets: ["AWSRDSData"]),
        .library(name: "AWSRUM", targets: ["AWSRUM"]),
        .library(name: "AWSRbin", targets: ["AWSRbin"]),
        .library(name: "AWSRedshift", targets: ["AWSRedshift"]),
        .library(name: "AWSRedshiftData", targets: ["AWSRedshiftData"]),
        .library(name: "AWSRedshiftServerless", targets: ["AWSRedshiftServerless"]),
        .library(name: "AWSRekognition", targets: ["AWSRekognition"]),
        .library(name: "AWSResiliencehub", targets: ["AWSResiliencehub"]),
        .library(name: "AWSResourceGroups", targets: ["AWSResourceGroups"]),
        .library(name: "AWSResourceGroupsTaggingAPI", targets: ["AWSResourceGroupsTaggingAPI"]),
        .library(name: "AWSRoboMaker", targets: ["AWSRoboMaker"]),
        .library(name: "AWSRolesAnywhere", targets: ["AWSRolesAnywhere"]),
        .library(name: "AWSRoute53", targets: ["AWSRoute53"]),
        .library(name: "AWSRoute53Domains", targets: ["AWSRoute53Domains"]),
        .library(name: "AWSRoute53RecoveryCluster", targets: ["AWSRoute53RecoveryCluster"]),
        .library(name: "AWSRoute53RecoveryControlConfig", targets: ["AWSRoute53RecoveryControlConfig"]),
        .library(name: "AWSRoute53RecoveryReadiness", targets: ["AWSRoute53RecoveryReadiness"]),
        .library(name: "AWSRoute53Resolver", targets: ["AWSRoute53Resolver"]),
        .library(name: "AWSS3", targets: ["AWSS3"]),
        .library(name: "AWSS3Control", targets: ["AWSS3Control"]),
        .library(name: "AWSS3Outposts", targets: ["AWSS3Outposts"]),
        .library(name: "AWSSES", targets: ["AWSSES"]),
        .library(name: "AWSSESv2", targets: ["AWSSESv2"]),
        .library(name: "AWSSFN", targets: ["AWSSFN"]),
        .library(name: "AWSSMS", targets: ["AWSSMS"]),
        .library(name: "AWSSNS", targets: ["AWSSNS"]),
        .library(name: "AWSSQS", targets: ["AWSSQS"]),
        .library(name: "AWSSSM", targets: ["AWSSSM"]),
        .library(name: "AWSSSMContacts", targets: ["AWSSSMContacts"]),
        .library(name: "AWSSSMIncidents", targets: ["AWSSSMIncidents"]),
        .library(name: "AWSSSO", targets: ["AWSSSO"]),
        .library(name: "AWSSSOAdmin", targets: ["AWSSSOAdmin"]),
        .library(name: "AWSSSOOIDC", targets: ["AWSSSOOIDC"]),
        .library(name: "AWSSTS", targets: ["AWSSTS"]),
        .library(name: "AWSSWF", targets: ["AWSSWF"]),
        .library(name: "AWSSageMaker", targets: ["AWSSageMaker"]),
        .library(name: "AWSSageMakerA2IRuntime", targets: ["AWSSageMakerA2IRuntime"]),
        .library(name: "AWSSageMakerFeatureStoreRuntime", targets: ["AWSSageMakerFeatureStoreRuntime"]),
        .library(name: "AWSSageMakerRuntime", targets: ["AWSSageMakerRuntime"]),
        .library(name: "AWSSagemakerEdge", targets: ["AWSSagemakerEdge"]),
        .library(name: "AWSSavingsplans", targets: ["AWSSavingsplans"]),
        .library(name: "AWSSchemas", targets: ["AWSSchemas"]),
        .library(name: "AWSSecretsManager", targets: ["AWSSecretsManager"]),
        .library(name: "AWSSecurityHub", targets: ["AWSSecurityHub"]),
        .library(name: "AWSServerlessApplicationRepository", targets: ["AWSServerlessApplicationRepository"]),
        .library(name: "AWSServiceCatalog", targets: ["AWSServiceCatalog"]),
        .library(name: "AWSServiceCatalogAppRegistry", targets: ["AWSServiceCatalogAppRegistry"]),
        .library(name: "AWSServiceDiscovery", targets: ["AWSServiceDiscovery"]),
        .library(name: "AWSServiceQuotas", targets: ["AWSServiceQuotas"]),
        .library(name: "AWSShield", targets: ["AWSShield"]),
        .library(name: "AWSSigner", targets: ["AWSSigner"]),
        .library(name: "AWSSnowDeviceManagement", targets: ["AWSSnowDeviceManagement"]),
        .library(name: "AWSSnowball", targets: ["AWSSnowball"]),
        .library(name: "AWSStorageGateway", targets: ["AWSStorageGateway"]),
        .library(name: "AWSSupport", targets: ["AWSSupport"]),
        .library(name: "AWSSupportApp", targets: ["AWSSupportApp"]),
        .library(name: "AWSSynthetics", targets: ["AWSSynthetics"]),
        .library(name: "AWSTextract", targets: ["AWSTextract"]),
        .library(name: "AWSTimestreamQuery", targets: ["AWSTimestreamQuery"]),
        .library(name: "AWSTimestreamWrite", targets: ["AWSTimestreamWrite"]),
        .library(name: "AWSTranscribe", targets: ["AWSTranscribe"]),
        .library(name: "AWSTranscribeStreaming", targets: ["AWSTranscribeStreaming"]),
        .library(name: "AWSTransfer", targets: ["AWSTransfer"]),
        .library(name: "AWSTranslate", targets: ["AWSTranslate"]),
        .library(name: "AWSVoiceID", targets: ["AWSVoiceID"]),
        .library(name: "AWSWAF", targets: ["AWSWAF"]),
        .library(name: "AWSWAFRegional", targets: ["AWSWAFRegional"]),
        .library(name: "AWSWAFV2", targets: ["AWSWAFV2"]),
        .library(name: "AWSWellArchitected", targets: ["AWSWellArchitected"]),
        .library(name: "AWSWisdom", targets: ["AWSWisdom"]),
        .library(name: "AWSWorkDocs", targets: ["AWSWorkDocs"]),
        .library(name: "AWSWorkLink", targets: ["AWSWorkLink"]),
        .library(name: "AWSWorkMail", targets: ["AWSWorkMail"]),
        .library(name: "AWSWorkMailMessageFlow", targets: ["AWSWorkMailMessageFlow"]),
        .library(name: "AWSWorkSpaces", targets: ["AWSWorkSpaces"]),
        .library(name: "AWSWorkSpacesWeb", targets: ["AWSWorkSpacesWeb"]),
        .library(name: "AWSXRay", targets: ["AWSXRay"]),
    ],
    dependencies: [
        .package(name: "AwsCrt", url: "https://github.com/awslabs/aws-crt-swift.git", .exact("0.2.2")),
        .package(name: "ClientRuntime", url: "https://github.com/awslabs/smithy-swift.git", .exact("0.3.0"))
    ],
    targets: [
        .target(
            name: "AWSClientRuntime",
            dependencies: [
                .product(name: "ClientRuntime", package: "ClientRuntime"),
                .product(name: "AwsCommonRuntimeKit", package: "AwsCrt")
            ],
            path: "./AWSClientRuntime/Sources"
        ),
        .testTarget(
            name: "AWSClientRuntimeTests",
            dependencies: [
                "AWSClientRuntime",
                .product(name: "SmithyTestUtil", package: "ClientRuntime"),
                .product(name: "ClientRuntime", package: "ClientRuntime")
            ],
            path: "./AWSClientRuntime/Tests"
        ),
        .target(name: "AWSACM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSACM"),
        .target(name: "AWSACMPCA", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSACMPCA"),
        .target(name: "AWSAPIGateway", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAPIGateway"),
        .target(name: "AWSAccessAnalyzer", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAccessAnalyzer"),
        .target(name: "AWSAccount", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAccount"),
        .target(name: "AWSAlexaForBusiness", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAlexaForBusiness"),
        .target(name: "AWSAmp", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAmp"),
        .target(name: "AWSAmplify", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAmplify"),
        .target(name: "AWSAmplifyBackend", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAmplifyBackend"),
        .target(name: "AWSAmplifyUIBuilder", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAmplifyUIBuilder"),
        .target(name: "AWSApiGatewayManagementApi", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApiGatewayManagementApi"),
        .target(name: "AWSApiGatewayV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApiGatewayV2"),
        .target(name: "AWSAppConfig", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppConfig"),
        .target(name: "AWSAppConfigData", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppConfigData"),
        .target(name: "AWSAppIntegrations", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppIntegrations"),
        .target(name: "AWSAppMesh", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppMesh"),
        .target(name: "AWSAppRunner", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppRunner"),
        .target(name: "AWSAppStream", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppStream"),
        .target(name: "AWSAppSync", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppSync"),
        .target(name: "AWSAppflow", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAppflow"),
        .target(name: "AWSApplicationAutoScaling", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApplicationAutoScaling"),
        .target(name: "AWSApplicationCostProfiler", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApplicationCostProfiler"),
        .target(name: "AWSApplicationDiscoveryService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApplicationDiscoveryService"),
        .target(name: "AWSApplicationInsights", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSApplicationInsights"),
        .target(name: "AWSAthena", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAthena"),
        .target(name: "AWSAuditManager", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAuditManager"),
        .target(name: "AWSAutoScaling", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAutoScaling"),
        .target(name: "AWSAutoScalingPlans", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSAutoScalingPlans"),
        .target(name: "AWSBackup", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBackup"),
        .target(name: "AWSBackupGateway", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBackupGateway"),
        .target(name: "AWSBackupStorage", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBackupStorage"),
        .target(name: "AWSBatch", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBatch"),
        .target(name: "AWSBillingconductor", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBillingconductor"),
        .target(name: "AWSBraket", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBraket"),
        .target(name: "AWSBudgets", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSBudgets"),
        .target(name: "AWSChime", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSChime"),
        .target(name: "AWSChimeSDKIdentity", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSChimeSDKIdentity"),
        .target(name: "AWSChimeSDKMediaPipelines", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSChimeSDKMediaPipelines"),
        .target(name: "AWSChimeSDKMeetings", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSChimeSDKMeetings"),
        .target(name: "AWSChimeSDKMessaging", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSChimeSDKMessaging"),
        .target(name: "AWSCloud9", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloud9"),
        .target(name: "AWSCloudControl", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudControl"),
        .target(name: "AWSCloudDirectory", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudDirectory"),
        .target(name: "AWSCloudFormation", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudFormation"),
        .target(name: "AWSCloudFront", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudFront"),
        .target(name: "AWSCloudHSM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudHSM"),
        .target(name: "AWSCloudHSMV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudHSMV2"),
        .target(name: "AWSCloudSearch", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudSearch"),
        .target(name: "AWSCloudSearchDomain", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudSearchDomain"),
        .target(name: "AWSCloudTrail", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudTrail"),
        .target(name: "AWSCloudWatch", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudWatch"),
        .target(name: "AWSCloudWatchEvents", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudWatchEvents"),
        .target(name: "AWSCloudWatchLogs", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCloudWatchLogs"),
        .target(name: "AWSCodeBuild", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeBuild"),
        .target(name: "AWSCodeCommit", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeCommit"),
        .target(name: "AWSCodeDeploy", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeDeploy"),
        .target(name: "AWSCodeGuruProfiler", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeGuruProfiler"),
        .target(name: "AWSCodeGuruReviewer", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeGuruReviewer"),
        .target(name: "AWSCodePipeline", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodePipeline"),
        .target(name: "AWSCodeStar", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeStar"),
        .target(name: "AWSCodeStarconnections", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeStarconnections"),
        .target(name: "AWSCodeartifact", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodeartifact"),
        .target(name: "AWSCodestarnotifications", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCodestarnotifications"),
        .target(name: "AWSCognitoIdentity", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCognitoIdentity"),
        .target(name: "AWSCognitoIdentityProvider", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCognitoIdentityProvider"),
        .target(name: "AWSCognitoSync", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCognitoSync"),
        .target(name: "AWSComprehend", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSComprehend"),
        .target(name: "AWSComprehendMedical", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSComprehendMedical"),
        .target(name: "AWSComputeOptimizer", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSComputeOptimizer"),
        .target(name: "AWSConfigService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSConfigService"),
        .target(name: "AWSConnect", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSConnect"),
        .target(name: "AWSConnectCampaigns", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSConnectCampaigns"),
        .target(name: "AWSConnectContactLens", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSConnectContactLens"),
        .target(name: "AWSConnectParticipant", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSConnectParticipant"),
        .target(name: "AWSControlTower", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSControlTower"),
        .target(name: "AWSCostExplorer", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCostExplorer"),
        .target(name: "AWSCostandUsageReportService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCostandUsageReportService"),
        .target(name: "AWSCustomerProfiles", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSCustomerProfiles"),
        .target(name: "AWSDAX", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDAX"),
        .target(name: "AWSDLM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDLM"),
        .target(name: "AWSDataBrew", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDataBrew"),
        .target(name: "AWSDataExchange", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDataExchange"),
        .target(name: "AWSDataPipeline", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDataPipeline"),
        .target(name: "AWSDataSync", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDataSync"),
        .target(name: "AWSDatabaseMigrationService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDatabaseMigrationService"),
        .target(name: "AWSDetective", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDetective"),
        .target(name: "AWSDevOpsGuru", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDevOpsGuru"),
        .target(name: "AWSDeviceFarm", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDeviceFarm"),
        .target(name: "AWSDirectConnect", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDirectConnect"),
        .target(name: "AWSDirectoryService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDirectoryService"),
        .target(name: "AWSDocDB", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDocDB"),
        .target(name: "AWSDrs", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDrs"),
        .target(name: "AWSDynamoDB", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDynamoDB"),
        .target(name: "AWSDynamoDBStreams", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSDynamoDBStreams"),
        .target(name: "AWSEBS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEBS"),
        .target(name: "AWSEC2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEC2"),
        .target(name: "AWSEC2InstanceConnect", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEC2InstanceConnect"),
        .target(name: "AWSECR", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSECR"),
        .target(name: "AWSECRPUBLIC", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSECRPUBLIC"),
        .target(name: "AWSECS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSECS"),
        .target(name: "AWSEFS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEFS"),
        .target(name: "AWSEKS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEKS"),
        .target(name: "AWSEMR", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEMR"),
        .target(name: "AWSEMRServerless", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEMRServerless"),
        .target(name: "AWSEMRcontainers", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEMRcontainers"),
        .target(name: "AWSElastiCache", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElastiCache"),
        .target(name: "AWSElasticBeanstalk", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticBeanstalk"),
        .target(name: "AWSElasticInference", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticInference"),
        .target(name: "AWSElasticLoadBalancing", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticLoadBalancing"),
        .target(name: "AWSElasticLoadBalancingv2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticLoadBalancingv2"),
        .target(name: "AWSElasticTranscoder", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticTranscoder"),
        .target(name: "AWSElasticsearchService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSElasticsearchService"),
        .target(name: "AWSEventBridge", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEventBridge"),
        .target(name: "AWSEvidently", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSEvidently"),
        .target(name: "AWSFMS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFMS"),
        .target(name: "AWSFSx", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFSx"),
        .target(name: "AWSFinspace", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFinspace"),
        .target(name: "AWSFinspacedata", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFinspacedata"),
        .target(name: "AWSFirehose", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFirehose"),
        .target(name: "AWSFis", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFis"),
        .target(name: "AWSForecast", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSForecast"),
        .target(name: "AWSForecastquery", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSForecastquery"),
        .target(name: "AWSFraudDetector", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSFraudDetector"),
        .target(name: "AWSGameLift", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGameLift"),
        .target(name: "AWSGameSparks", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGameSparks"),
        .target(name: "AWSGlacier", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGlacier"),
        .target(name: "AWSGlobalAccelerator", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGlobalAccelerator"),
        .target(name: "AWSGlue", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGlue"),
        .target(name: "AWSGrafana", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGrafana"),
        .target(name: "AWSGreengrass", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGreengrass"),
        .target(name: "AWSGreengrassV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGreengrassV2"),
        .target(name: "AWSGroundStation", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGroundStation"),
        .target(name: "AWSGuardDuty", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSGuardDuty"),
        .target(name: "AWSHealth", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSHealth"),
        .target(name: "AWSHealthLake", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSHealthLake"),
        .target(name: "AWSHoneycode", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSHoneycode"),
        .target(name: "AWSIAM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIAM"),
        .target(name: "AWSIdentitystore", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIdentitystore"),
        .target(name: "AWSImagebuilder", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSImagebuilder"),
        .target(name: "AWSInspector", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSInspector"),
        .target(name: "AWSInspector2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSInspector2"),
        .target(name: "AWSIoT", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoT"),
        .target(name: "AWSIoT1ClickDevicesService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoT1ClickDevicesService"),
        .target(name: "AWSIoT1ClickProjects", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoT1ClickProjects"),
        .target(name: "AWSIoTAnalytics", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTAnalytics"),
        .target(name: "AWSIoTDataPlane", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTDataPlane"),
        .target(name: "AWSIoTEvents", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTEvents"),
        .target(name: "AWSIoTEventsData", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTEventsData"),
        .target(name: "AWSIoTFleetHub", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTFleetHub"),
        .target(name: "AWSIoTFleetWise", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTFleetWise"),
        .target(name: "AWSIoTJobsDataPlane", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTJobsDataPlane"),
        .target(name: "AWSIoTSecureTunneling", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTSecureTunneling"),
        .target(name: "AWSIoTSiteWise", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTSiteWise"),
        .target(name: "AWSIoTThingsGraph", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTThingsGraph"),
        .target(name: "AWSIoTTwinMaker", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTTwinMaker"),
        .target(name: "AWSIoTWireless", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIoTWireless"),
        .target(name: "AWSIotDeviceAdvisor", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIotDeviceAdvisor"),
        .target(name: "AWSIvs", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIvs"),
        .target(name: "AWSIvschat", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSIvschat"),
        .target(name: "AWSKMS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKMS"),
        .target(name: "AWSKafka", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKafka"),
        .target(name: "AWSKafkaConnect", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKafkaConnect"),
        .target(name: "AWSKendra", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKendra"),
        .target(name: "AWSKeyspaces", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKeyspaces"),
        .target(name: "AWSKinesis", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesis"),
        .target(name: "AWSKinesisAnalytics", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisAnalytics"),
        .target(name: "AWSKinesisAnalyticsV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisAnalyticsV2"),
        .target(name: "AWSKinesisVideo", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisVideo"),
        .target(name: "AWSKinesisVideoArchivedMedia", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisVideoArchivedMedia"),
        .target(name: "AWSKinesisVideoMedia", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisVideoMedia"),
        .target(name: "AWSKinesisVideoSignaling", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSKinesisVideoSignaling"),
        .target(name: "AWSLakeFormation", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLakeFormation"),
        .target(name: "AWSLambda", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLambda"),
        .target(name: "AWSLexModelBuildingService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLexModelBuildingService"),
        .target(name: "AWSLexModelsV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLexModelsV2"),
        .target(name: "AWSLexRuntimeService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLexRuntimeService"),
        .target(name: "AWSLexRuntimeV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLexRuntimeV2"),
        .target(name: "AWSLicenseManager", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLicenseManager"),
        .target(name: "AWSLicenseManagerUserSubscriptions", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLicenseManagerUserSubscriptions"),
        .target(name: "AWSLightsail", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLightsail"),
        .target(name: "AWSLocation", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLocation"),
        .target(name: "AWSLookoutEquipment", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLookoutEquipment"),
        .target(name: "AWSLookoutMetrics", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLookoutMetrics"),
        .target(name: "AWSLookoutVision", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSLookoutVision"),
        .target(name: "AWSM2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSM2"),
        .target(name: "AWSMTurk", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMTurk"),
        .target(name: "AWSMWAA", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMWAA"),
        .target(name: "AWSMachineLearning", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMachineLearning"),
        .target(name: "AWSMacie", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMacie"),
        .target(name: "AWSMacie2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMacie2"),
        .target(name: "AWSManagedBlockchain", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSManagedBlockchain"),
        .target(name: "AWSMarketplaceCatalog", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMarketplaceCatalog"),
        .target(name: "AWSMarketplaceCommerceAnalytics", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMarketplaceCommerceAnalytics"),
        .target(name: "AWSMarketplaceEntitlementService", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMarketplaceEntitlementService"),
        .target(name: "AWSMarketplaceMetering", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMarketplaceMetering"),
        .target(name: "AWSMediaConnect", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaConnect"),
        .target(name: "AWSMediaConvert", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaConvert"),
        .target(name: "AWSMediaLive", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaLive"),
        .target(name: "AWSMediaPackage", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaPackage"),
        .target(name: "AWSMediaPackageVod", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaPackageVod"),
        .target(name: "AWSMediaStore", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaStore"),
        .target(name: "AWSMediaStoreData", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaStoreData"),
        .target(name: "AWSMediaTailor", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMediaTailor"),
        .target(name: "AWSMemoryDB", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMemoryDB"),
        .target(name: "AWSMgn", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMgn"),
        .target(name: "AWSMigrationHub", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMigrationHub"),
        .target(name: "AWSMigrationHubConfig", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMigrationHubConfig"),
        .target(name: "AWSMigrationHubOrchestrator", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMigrationHubOrchestrator"),
        .target(name: "AWSMigrationHubRefactorSpaces", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMigrationHubRefactorSpaces"),
        .target(name: "AWSMigrationHubStrategy", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMigrationHubStrategy"),
        .target(name: "AWSMobile", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMobile"),
        .target(name: "AWSMq", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSMq"),
        .target(name: "AWSNeptune", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSNeptune"),
        .target(name: "AWSNetworkFirewall", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSNetworkFirewall"),
        .target(name: "AWSNetworkManager", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSNetworkManager"),
        .target(name: "AWSNimble", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSNimble"),
        .target(name: "AWSOpenSearch", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSOpenSearch"),
        .target(name: "AWSOpsWorks", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSOpsWorks"),
        .target(name: "AWSOpsWorksCM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSOpsWorksCM"),
        .target(name: "AWSOrganizations", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSOrganizations"),
        .target(name: "AWSOutposts", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSOutposts"),
        .target(name: "AWSPI", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPI"),
        .target(name: "AWSPanorama", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPanorama"),
        .target(name: "AWSPersonalize", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPersonalize"),
        .target(name: "AWSPersonalizeEvents", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPersonalizeEvents"),
        .target(name: "AWSPersonalizeRuntime", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPersonalizeRuntime"),
        .target(name: "AWSPinpoint", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPinpoint"),
        .target(name: "AWSPinpointEmail", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPinpointEmail"),
        .target(name: "AWSPinpointSMSVoice", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPinpointSMSVoice"),
        .target(name: "AWSPinpointSMSVoiceV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPinpointSMSVoiceV2"),
        .target(name: "AWSPolly", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPolly"),
        .target(name: "AWSPricing", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPricing"),
        .target(name: "AWSPrivateNetworks", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSPrivateNetworks"),
        .target(name: "AWSProton", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSProton"),
        .target(name: "AWSQLDB", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSQLDB"),
        .target(name: "AWSQLDBSession", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSQLDBSession"),
        .target(name: "AWSQuickSight", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSQuickSight"),
        .target(name: "AWSRAM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRAM"),
        .target(name: "AWSRDS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRDS"),
        .target(name: "AWSRDSData", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRDSData"),
        .target(name: "AWSRUM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRUM"),
        .target(name: "AWSRbin", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRbin"),
        .target(name: "AWSRedshift", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRedshift"),
        .target(name: "AWSRedshiftData", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRedshiftData"),
        .target(name: "AWSRedshiftServerless", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRedshiftServerless"),
        .target(name: "AWSRekognition", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRekognition"),
        .target(name: "AWSResiliencehub", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSResiliencehub"),
        .target(name: "AWSResourceGroups", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSResourceGroups"),
        .target(name: "AWSResourceGroupsTaggingAPI", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSResourceGroupsTaggingAPI"),
        .target(name: "AWSRoboMaker", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoboMaker"),
        .target(name: "AWSRolesAnywhere", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRolesAnywhere"),
        .target(name: "AWSRoute53", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53"),
        .target(name: "AWSRoute53Domains", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53Domains"),
        .target(name: "AWSRoute53RecoveryCluster", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53RecoveryCluster"),
        .target(name: "AWSRoute53RecoveryControlConfig", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53RecoveryControlConfig"),
        .target(name: "AWSRoute53RecoveryReadiness", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53RecoveryReadiness"),
        .target(name: "AWSRoute53Resolver", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSRoute53Resolver"),
        .target(name: "AWSS3", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSS3"),
        .target(name: "AWSS3Control", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSS3Control"),
        .target(name: "AWSS3Outposts", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSS3Outposts"),
        .target(name: "AWSSES", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSES"),
        .target(name: "AWSSESv2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSESv2"),
        .target(name: "AWSSFN", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSFN"),
        .target(name: "AWSSMS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSMS"),
        .target(name: "AWSSNS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSNS"),
        .target(name: "AWSSQS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSQS"),
        .target(name: "AWSSSM", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSM"),
        .target(name: "AWSSSMContacts", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSMContacts"),
        .target(name: "AWSSSMIncidents", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSMIncidents"),
        .target(name: "AWSSSO", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSO"),
        .target(name: "AWSSSOAdmin", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSOAdmin"),
        .target(name: "AWSSSOOIDC", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSSOOIDC"),
        .target(name: "AWSSTS", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSTS"),
        .target(name: "AWSSWF", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSWF"),
        .target(name: "AWSSageMaker", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSageMaker"),
        .target(name: "AWSSageMakerA2IRuntime", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSageMakerA2IRuntime"),
        .target(name: "AWSSageMakerFeatureStoreRuntime", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSageMakerFeatureStoreRuntime"),
        .target(name: "AWSSageMakerRuntime", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSageMakerRuntime"),
        .target(name: "AWSSagemakerEdge", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSagemakerEdge"),
        .target(name: "AWSSavingsplans", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSavingsplans"),
        .target(name: "AWSSchemas", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSchemas"),
        .target(name: "AWSSecretsManager", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSecretsManager"),
        .target(name: "AWSSecurityHub", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSecurityHub"),
        .target(name: "AWSServerlessApplicationRepository", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSServerlessApplicationRepository"),
        .target(name: "AWSServiceCatalog", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSServiceCatalog"),
        .target(name: "AWSServiceCatalogAppRegistry", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSServiceCatalogAppRegistry"),
        .target(name: "AWSServiceDiscovery", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSServiceDiscovery"),
        .target(name: "AWSServiceQuotas", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSServiceQuotas"),
        .target(name: "AWSShield", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSShield"),
        .target(name: "AWSSigner", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSigner"),
        .target(name: "AWSSnowDeviceManagement", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSnowDeviceManagement"),
        .target(name: "AWSSnowball", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSnowball"),
        .target(name: "AWSStorageGateway", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSStorageGateway"),
        .target(name: "AWSSupport", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSupport"),
        .target(name: "AWSSupportApp", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSupportApp"),
        .target(name: "AWSSynthetics", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSSynthetics"),
        .target(name: "AWSTextract", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTextract"),
        .target(name: "AWSTimestreamQuery", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTimestreamQuery"),
        .target(name: "AWSTimestreamWrite", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTimestreamWrite"),
        .target(name: "AWSTranscribe", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTranscribe"),
        .target(name: "AWSTranscribeStreaming", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTranscribeStreaming"),
        .target(name: "AWSTransfer", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTransfer"),
        .target(name: "AWSTranslate", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSTranslate"),
        .target(name: "AWSVoiceID", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSVoiceID"),
        .target(name: "AWSWAF", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWAF"),
        .target(name: "AWSWAFRegional", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWAFRegional"),
        .target(name: "AWSWAFV2", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWAFV2"),
        .target(name: "AWSWellArchitected", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWellArchitected"),
        .target(name: "AWSWisdom", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWisdom"),
        .target(name: "AWSWorkDocs", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkDocs"),
        .target(name: "AWSWorkLink", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkLink"),
        .target(name: "AWSWorkMail", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkMail"),
        .target(name: "AWSWorkMailMessageFlow", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkMailMessageFlow"),
        .target(name: "AWSWorkSpaces", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkSpaces"),
        .target(name: "AWSWorkSpacesWeb", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSWorkSpacesWeb"),
        .target(name: "AWSXRay", dependencies: [.product(name: "ClientRuntime", package: "ClientRuntime"), "AWSClientRuntime"], path: "./release/AWSXRay"),
        ]
)
