// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct PutProfileObjectOutput: Equatable {
    /// <p>The unique identifier of the profile object generated by the service.</p>
    public let profileObjectUniqueKey: String?

    public init (
        profileObjectUniqueKey: String? = nil
    )
    {
        self.profileObjectUniqueKey = profileObjectUniqueKey
    }
}
