// Code generated by smithy-swift-codegen. DO NOT EDIT!



public enum EmbeddingIdentityType {
    case anonymous
    case iam
    case quicksight
    case sdkUnknown(String)
}

extension EmbeddingIdentityType : Equatable, RawRepresentable, Codable, CaseIterable, Hashable {
    public static var allCases: [EmbeddingIdentityType] {
        return [
            .anonymous,
            .iam,
            .quicksight,
            .sdkUnknown("")
        ]
    }
    public init?(rawValue: String) {
        let value = Self.allCases.first(where: { $0.rawValue == rawValue })
        self = value ?? Self.sdkUnknown(rawValue)
    }
    public var rawValue: String {
        switch self {
        case .anonymous: return "ANONYMOUS"
        case .iam: return "IAM"
        case .quicksight: return "QUICKSIGHT"
        case let .sdkUnknown(s): return s
        }
    }
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(RawValue.self)
        self = EmbeddingIdentityType(rawValue: rawValue) ?? EmbeddingIdentityType.sdkUnknown(rawValue)
    }
}
