// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension S3Source: CustomDebugStringConvertible {
    public var debugDescription: String {
        "S3Source(dataSourceArn: \(String(describing: dataSourceArn)), inputColumns: \(String(describing: inputColumns)), uploadSettings: \(String(describing: uploadSettings)))"}
}
