// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetTableVersionsOutputResponse: HttpResponseBinding {
    public init (httpResponse: HttpResponse, decoder: ResponseDecoder? = nil) throws {
        if case .data(let data) = httpResponse.body,
            let unwrappedData = data,
            let responseDecoder = decoder {
            let output: GetTableVersionsOutputResponseBody = try responseDecoder.decode(responseBody: unwrappedData)
            self.nextToken = output.nextToken
            self.tableVersions = output.tableVersions
        } else {
            self.nextToken = nil
            self.tableVersions = nil
        }
    }
}
