// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// <p>A workflow run is an execution of a workflow providing all the runtime information.</p>
public struct WorkflowRun: Equatable {
    /// <p>The date and time when the workflow run completed.</p>
    public let completedOn: Date?
    /// <p>This error message describes any error that may have occurred in starting the workflow run. Currently the only error message is "Concurrent runs exceeded for workflow: <code>foo</code>."</p>
    public let errorMessage: String?
    /// <p>The graph representing all the AWS Glue components that belong to the workflow as nodes and directed
    ///       connections between them as edges.</p>
    public let graph: WorkflowGraph?
    /// <p>Name of the workflow that was executed.</p>
    public let name: String?
    /// <p>The ID of the previous workflow run.</p>
    public let previousRunId: String?
    /// <p>The date and time when the workflow run was started.</p>
    public let startedOn: Date?
    /// <p>The statistics of the run.</p>
    public let statistics: WorkflowRunStatistics?
    /// <p>The status of the workflow run.</p>
    public let status: WorkflowRunStatus?
    /// <p>The ID of this workflow run.</p>
    public let workflowRunId: String?
    /// <p>The workflow run properties which were set during the run.</p>
    public let workflowRunProperties: [String:String]?

    public init (
        completedOn: Date? = nil,
        errorMessage: String? = nil,
        graph: WorkflowGraph? = nil,
        name: String? = nil,
        previousRunId: String? = nil,
        startedOn: Date? = nil,
        statistics: WorkflowRunStatistics? = nil,
        status: WorkflowRunStatus? = nil,
        workflowRunId: String? = nil,
        workflowRunProperties: [String:String]? = nil
    )
    {
        self.completedOn = completedOn
        self.errorMessage = errorMessage
        self.graph = graph
        self.name = name
        self.previousRunId = previousRunId
        self.startedOn = startedOn
        self.statistics = statistics
        self.status = status
        self.workflowRunId = workflowRunId
        self.workflowRunProperties = workflowRunProperties
    }
}

extension WorkflowRun: CustomDebugStringConvertible {
    public var debugDescription: String {
        "WorkflowRun(completedOn: \(String(describing: completedOn)), errorMessage: \(String(describing: errorMessage)), graph: \(String(describing: graph)), name: \(String(describing: name)), previousRunId: \(String(describing: previousRunId)), startedOn: \(String(describing: startedOn)), statistics: \(String(describing: statistics)), status: \(String(describing: status)), workflowRunId: \(String(describing: workflowRunId)), workflowRunProperties: \(String(describing: workflowRunProperties)))"}
}
