// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension VpcInterface: CustomDebugStringConvertible {
    public var debugDescription: String {
        "VpcInterface(name: \(String(describing: name)), networkInterfaceIds: \(String(describing: networkInterfaceIds)), networkInterfaceType: \(String(describing: networkInterfaceType)), roleArn: \(String(describing: roleArn)), securityGroupIds: \(String(describing: securityGroupIds)), subnetId: \(String(describing: subnetId)))"}
}
