// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct QueryInput: Equatable {
    /// <p>
    ///        Unique, case-sensitive string of up to 64 ASCII characters that you specify when you make a Query request.
    ///        Providing a <code>ClientToken</code> makes the call to <code>Query</code> idempotent, meaning that multiple identical calls
    ///        have the same effect as one single call.
    ///     </p>
    ///
    ///          <p>Your query request will fail in the following cases:</p>
    ///          <ul>
    ///             <li>
    ///                <p>
    ///                   If you submit a request with the same client token outside the 5-minute idepotency window.
    ///                </p>
    ///            </li>
    ///             <li>
    ///                <p>
    ///                   If you submit a request with the same client token but a change in other parameters within the 5-minute idempotency window.
    ///                </p>
    ///            </li>
    ///          </ul>
    ///
    ///          <p>
    ///       After 4 hours, any request with the same client token is treated as a new request.
    ///       </p>
    public var clientToken: String?
    /// <p>
    ///       The total number of rows to return in the output. If the total number of rows available
    ///       is more than the value specified, a NextToken is provided in the command's output.
    ///       To resume pagination, provide the NextToken value in the starting-token argument of a
    ///       subsequent command.
    ///     </p>
    public let maxRows: Int?
    /// <p>
    ///        A pagination token passed to get a set of results.
    ///     </p>
    public let nextToken: String?
    /// <p>
    ///             The query to be executed by Timestream.
    ///         </p>
    public let queryString: String?

    public init (
        clientToken: String? = nil,
        maxRows: Int? = nil,
        nextToken: String? = nil,
        queryString: String? = nil
    )
    {
        self.clientToken = clientToken
        self.maxRows = maxRows
        self.nextToken = nextToken
        self.queryString = queryString
    }
}

extension QueryInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "QueryInput(clientToken: \(String(describing: clientToken)), maxRows: \(String(describing: maxRows)), nextToken: \(String(describing: nextToken)), queryString: \(String(describing: queryString)))"}
}
