// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetBucketCorsOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetBucketCorsOutput(cORSRules: \(String(describing: cORSRules)))"}
}
