// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension PutPublicAccessBlockInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "PutPublicAccessBlockInput(bucket: \(String(describing: bucket)), contentMD5: \(String(describing: contentMD5)), expectedBucketOwner: \(String(describing: expectedBucketOwner)), publicAccessBlockConfiguration: \(String(describing: publicAccessBlockConfiguration)))"}
}
