// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension S3Source: CustomDebugStringConvertible {
    public var debugDescription: String {
        "S3Source(bucketName: \(String(describing: bucketName)), key: \(String(describing: key)), version: \(String(describing: version)))"}
}
