// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct BatchDisassociateServiceActionFromProvisioningArtifactOutputResponse: Equatable {
    /// <p>An object that contains a list of errors, along with information to help you identify the self-service action.</p>
    public let failedServiceActionAssociations: [FailedServiceActionAssociation]?

    public init (
        failedServiceActionAssociations: [FailedServiceActionAssociation]? = nil
    )
    {
        self.failedServiceActionAssociations = failedServiceActionAssociations
    }
}

extension BatchDisassociateServiceActionFromProvisioningArtifactOutputResponse: CustomDebugStringConvertible {
    public var debugDescription: String {
        "BatchDisassociateServiceActionFromProvisioningArtifactOutputResponse(failedServiceActionAssociations: \(String(describing: failedServiceActionAssociations)))"}
}
