// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ExportTaskStatus: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ExportTaskStatus(code: \(String(describing: code)), message: \(String(describing: message)))"}
}
