// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeScalingPlansInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeScalingPlansInput(applicationSources: \(String(describing: applicationSources)), maxResults: \(String(describing: maxResults)), nextToken: \(String(describing: nextToken)), scalingPlanNames: \(String(describing: scalingPlanNames)), scalingPlanVersion: \(String(describing: scalingPlanVersion)))"}
}
