// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListGroupsOutputResponse: Equatable {
    /// <p>A list of <code>Group</code> objects in the identity store.</p>
    public let groups: [Group]?
    /// <p>The pagination token used for the <code>ListUsers</code> and <code>ListGroups</code> APIs. This value is generated by the identity store service and is returned in the API response if the total results are more than the size of one page, and when this token is used in the API request to search for the next page.</p>
    public let nextToken: String?

    public init (
        groups: [Group]? = nil,
        nextToken: String? = nil
    )
    {
        self.groups = groups
        self.nextToken = nextToken
    }
}

extension ListGroupsOutputResponse: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ListGroupsOutputResponse(groups: \(String(describing: groups)), nextToken: \(String(describing: nextToken)))"}
}
