// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetJobOutputResponse: Equatable {
    /// <p> Describes an execution job for an Amplify app. </p>
    public let job: Job?

    public init (
        job: Job? = nil
    )
    {
        self.job = job
    }
}

extension GetJobOutputResponse: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetJobOutputResponse(job: \(String(describing: job)))"}
}
