// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// <p>The filters applied to Data Store query.</p>
public struct DatastoreFilter: Equatable {
    /// <p>A filter that allows the user to set cutoff dates for records. All Data Stores created
    ///          after the specified date will be included in the results.</p>
    public let createdAfter: Date?
    /// <p>A filter that allows the user to set cutoff dates for records. All Data Stores created
    ///          before the specified date will be included in the results. </p>
    public let createdBefore: Date?
    /// <p>Allows the user to filter Data Store results by name.</p>
    public let datastoreName: String?
    /// <p>Allows the user to filter Data Store results by status.</p>
    public let datastoreStatus: DatastoreStatus?

    public init (
        createdAfter: Date? = nil,
        createdBefore: Date? = nil,
        datastoreName: String? = nil,
        datastoreStatus: DatastoreStatus? = nil
    )
    {
        self.createdAfter = createdAfter
        self.createdBefore = createdBefore
        self.datastoreName = datastoreName
        self.datastoreStatus = datastoreStatus
    }
}
