// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension BatchCreateDelegationByAssessmentOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "BatchCreateDelegationByAssessmentOutput(delegations: \(String(describing: delegations)), errors: \(String(describing: errors)))"}
}
