// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Framework: CustomDebugStringConvertible {
    public var debugDescription: String {
        "Framework(arn: \(String(describing: arn)), complianceType: \(String(describing: complianceType)), controlSets: \(String(describing: controlSets)), controlSources: \(String(describing: controlSources)), createdAt: \(String(describing: createdAt)), createdBy: \(String(describing: createdBy)), description: \(String(describing: description)), id: \(String(describing: id)), lastUpdatedAt: \(String(describing: lastUpdatedAt)), lastUpdatedBy: \(String(describing: lastUpdatedBy)), logo: \(String(describing: logo)), name: \(String(describing: name)), tags: \(String(describing: tags)), type: \(String(describing: type)))"}
}
