// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Lifecycle Cutover finalized</p>
public struct LifeCycleLastCutoverFinalized: Equatable {
    /// <p>Lifecycle Cutover finalized date and time.</p>
    public let apiCallDateTime: String?

    public init (
        apiCallDateTime: String? = nil
    )
    {
        self.apiCallDateTime = apiCallDateTime
    }
}
