// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DeleteAssessmentRunInputBody: Equatable {
    public let assessmentRunArn: String?
}

extension DeleteAssessmentRunInputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case assessmentRunArn
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let assessmentRunArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .assessmentRunArn)
        assessmentRunArn = assessmentRunArnDecoded
    }
}
