// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeAssessmentTemplatesInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeAssessmentTemplatesInput(assessmentTemplateArns: \(String(describing: assessmentTemplateArns)))"}
}
