// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetDeploymentInput: Encodable, Reflection {
    enum CodingKeys: String, CodingKey {
        case deploymentId
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let deploymentId = deploymentId {
            try encodeContainer.encode(deploymentId, forKey: .deploymentId)
        }
    }
}
