// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct RegisterJobDefinitionOutputBody: Equatable {
    public let jobDefinitionName: String?
    public let jobDefinitionArn: String?
    public let revision: Int
}

extension RegisterJobDefinitionOutputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case jobDefinitionArn
        case jobDefinitionName
        case revision
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let jobDefinitionNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .jobDefinitionName)
        jobDefinitionName = jobDefinitionNameDecoded
        let jobDefinitionArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .jobDefinitionArn)
        jobDefinitionArn = jobDefinitionArnDecoded
        let revisionDecoded = try containerValues.decode(Int.self, forKey: .revision)
        revision = revisionDecoded
    }
}
