// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DescribeDeviceOutput: HttpResponseBinding {
    public init (httpResponse: HttpResponse, decoder: ResponseDecoder? = nil) throws {
        if case .data(let data) = httpResponse.body,
            let unwrappedData = data,
            let responseDecoder = decoder {
            let output: DescribeDeviceOutputBody = try responseDecoder.decode(responseBody: unwrappedData)
            self.deviceDescription = output.deviceDescription
        } else {
            self.deviceDescription = nil
        }
    }
}
