// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DisassociateServiceRoleFromAccountInputBody: Equatable {
}

extension DisassociateServiceRoleFromAccountInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
