// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetCoreDefinitionVersionInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetCoreDefinitionVersionInput(coreDefinitionId: \(String(describing: coreDefinitionId)), coreDefinitionVersionId: \(String(describing: coreDefinitionVersionId)))"}
}
