// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetLoggerDefinitionVersionInputBody: Equatable {
}

extension GetLoggerDefinitionVersionInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
