// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>The updated note.</p>
public struct NoteUpdate: Equatable {
    /// <p>The updated note text.</p>
    public let text: String?
    /// <p>The principal that updated the note.</p>
    public let updatedBy: String?

    public init (
        text: String? = nil,
        updatedBy: String? = nil
    )
    {
        self.text = text
        self.updatedBy = updatedBy
    }
}

extension NoteUpdate: CustomDebugStringConvertible {
    public var debugDescription: String {
        "NoteUpdate(text: \(String(describing: text)), updatedBy: \(String(describing: updatedBy)))"}
}
