excluded:
  - Tests
  - .build

analyzer_rules:
  - unused_import
  - unused_declaration

disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
  - compiler_protocol_init
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - syntactic_sugar
  - unused_capture_list

opt_in_rules:
  - empty_count

# configurable rules can be customized from this configuration file
force_cast: warning
closing_brace: error
colon:
  severity: error
comma: error
empty_count: warning
empty_enum_arguments: error
function_body_length:
  warning: 100
  error: 150
identifier_name:
  excluded:
    - id
    - of
    - or
line_length:
  warning: 120
  error: 160
opening_brace: error
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
