// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetRecommendationError: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetRecommendationError(code: \(String(describing: code)), identifier: \(String(describing: identifier)), message: \(String(describing: message)))"}
}
