// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension AssociateResourceOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "AssociateResourceOutput(applicationArn: \(String(describing: applicationArn)), resourceArn: \(String(describing: resourceArn)))"}
}
