// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CancelDataRepositoryTaskInputHeadersMiddleware: Middleware {
    public let id: String = "CancelDataRepositoryTaskInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelDataRepositoryTaskInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelDataRepositoryTaskOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelDataRepositoryTaskInput>
    public typealias MOutput = OperationOutput<CancelDataRepositoryTaskOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelDataRepositoryTaskOutputError>
}

public struct CancelDataRepositoryTaskInputQueryItemMiddleware: Middleware {
    public let id: String = "CancelDataRepositoryTaskInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelDataRepositoryTaskInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelDataRepositoryTaskOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelDataRepositoryTaskInput>
    public typealias MOutput = OperationOutput<CancelDataRepositoryTaskOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelDataRepositoryTaskOutputError>
}

public struct CancelDataRepositoryTaskInputBodyMiddleware: Middleware {
    public let id: String = "CancelDataRepositoryTaskInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelDataRepositoryTaskInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelDataRepositoryTaskOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            if try !input.operationInput.allPropertiesAreNull() {
                let encoder = context.getEncoder()
                let data = try encoder.encode(input.operationInput)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            }
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelDataRepositoryTaskInput>
    public typealias MOutput = OperationOutput<CancelDataRepositoryTaskOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelDataRepositoryTaskOutputError>
}

extension CancelDataRepositoryTaskInput: Encodable, Reflection {
    enum CodingKeys: String, CodingKey {
        case taskId = "TaskId"
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let taskId = taskId {
            try encodeContainer.encode(taskId, forKey: .taskId)
        }
    }
}
