// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension EmailTemplateResponse: Codable, Reflection {
    enum CodingKeys: String, CodingKey {
        case arn = "Arn"
        case creationDate = "CreationDate"
        case defaultSubstitutions = "DefaultSubstitutions"
        case htmlPart = "HtmlPart"
        case lastModifiedDate = "LastModifiedDate"
        case recommenderId = "RecommenderId"
        case subject = "Subject"
        case templateDescription = "TemplateDescription"
        case templateName = "TemplateName"
        case templateType = "TemplateType"
        case textPart = "TextPart"
        case version = "Version"
        case tags = "tags"
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let arn = arn {
            try encodeContainer.encode(arn, forKey: .arn)
        }
        if let creationDate = creationDate {
            try encodeContainer.encode(creationDate, forKey: .creationDate)
        }
        if let defaultSubstitutions = defaultSubstitutions {
            try encodeContainer.encode(defaultSubstitutions, forKey: .defaultSubstitutions)
        }
        if let htmlPart = htmlPart {
            try encodeContainer.encode(htmlPart, forKey: .htmlPart)
        }
        if let lastModifiedDate = lastModifiedDate {
            try encodeContainer.encode(lastModifiedDate, forKey: .lastModifiedDate)
        }
        if let recommenderId = recommenderId {
            try encodeContainer.encode(recommenderId, forKey: .recommenderId)
        }
        if let subject = subject {
            try encodeContainer.encode(subject, forKey: .subject)
        }
        if let templateDescription = templateDescription {
            try encodeContainer.encode(templateDescription, forKey: .templateDescription)
        }
        if let templateName = templateName {
            try encodeContainer.encode(templateName, forKey: .templateName)
        }
        if let templateType = templateType {
            try encodeContainer.encode(templateType.rawValue, forKey: .templateType)
        }
        if let textPart = textPart {
            try encodeContainer.encode(textPart, forKey: .textPart)
        }
        if let version = version {
            try encodeContainer.encode(version, forKey: .version)
        }
        if let tags = tags {
            var tagsContainer = encodeContainer.nestedContainer(keyedBy: Key.self, forKey: .tags)
            for (dictKey0, mapof__string0) in tags {
                try tagsContainer.encode(mapof__string0, forKey: Key(stringValue: dictKey0))
            }
        }
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let arnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .arn)
        arn = arnDecoded
        let creationDateDecoded = try containerValues.decodeIfPresent(String.self, forKey: .creationDate)
        creationDate = creationDateDecoded
        let defaultSubstitutionsDecoded = try containerValues.decodeIfPresent(String.self, forKey: .defaultSubstitutions)
        defaultSubstitutions = defaultSubstitutionsDecoded
        let htmlPartDecoded = try containerValues.decodeIfPresent(String.self, forKey: .htmlPart)
        htmlPart = htmlPartDecoded
        let lastModifiedDateDecoded = try containerValues.decodeIfPresent(String.self, forKey: .lastModifiedDate)
        lastModifiedDate = lastModifiedDateDecoded
        let recommenderIdDecoded = try containerValues.decodeIfPresent(String.self, forKey: .recommenderId)
        recommenderId = recommenderIdDecoded
        let subjectDecoded = try containerValues.decodeIfPresent(String.self, forKey: .subject)
        subject = subjectDecoded
        let tagsContainer = try containerValues.decodeIfPresent([String: String?].self, forKey: .tags)
        var tagsDecoded0: [String:String]? = nil
        if let tagsContainer = tagsContainer {
            tagsDecoded0 = [String:String]()
            for (key0, __string0) in tagsContainer {
                if let __string0 = __string0 {
                    tagsDecoded0?[key0] = __string0
                }
            }
        }
        tags = tagsDecoded0
        let templateDescriptionDecoded = try containerValues.decodeIfPresent(String.self, forKey: .templateDescription)
        templateDescription = templateDescriptionDecoded
        let templateNameDecoded = try containerValues.decodeIfPresent(String.self, forKey: .templateName)
        templateName = templateNameDecoded
        let templateTypeDecoded = try containerValues.decodeIfPresent(TemplateType.self, forKey: .templateType)
        templateType = templateTypeDecoded
        let textPartDecoded = try containerValues.decodeIfPresent(String.self, forKey: .textPart)
        textPart = textPartDecoded
        let versionDecoded = try containerValues.decodeIfPresent(String.self, forKey: .version)
        version = versionDecoded
    }
}
