// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListObjectVersionsInput: ClientRuntime.QueryItemProvider {
    public var queryItems: [ClientRuntime.URLQueryItem] {
        var items = [ClientRuntime.URLQueryItem]()
        items.append(ClientRuntime.URLQueryItem(name: "versions", value: nil))
        if let versionIdMarker = versionIdMarker {
            let versionIdMarkerQueryItem = ClientRuntime.URLQueryItem(name: "version-id-marker".urlPercentEncoding(), value: Swift.String(versionIdMarker).urlPercentEncoding())
            items.append(versionIdMarkerQueryItem)
        }
        if let delimiter = delimiter {
            let delimiterQueryItem = ClientRuntime.URLQueryItem(name: "delimiter".urlPercentEncoding(), value: Swift.String(delimiter).urlPercentEncoding())
            items.append(delimiterQueryItem)
        }
        if let encodingType = encodingType {
            let encodingTypeQueryItem = ClientRuntime.URLQueryItem(name: "encoding-type".urlPercentEncoding(), value: Swift.String(encodingType.rawValue).urlPercentEncoding())
            items.append(encodingTypeQueryItem)
        }
        if let `prefix` = `prefix` {
            let prefixQueryItem = ClientRuntime.URLQueryItem(name: "prefix".urlPercentEncoding(), value: Swift.String(`prefix`).urlPercentEncoding())
            items.append(prefixQueryItem)
        }
        if maxKeys != 0 {
            let maxKeysQueryItem = ClientRuntime.URLQueryItem(name: "max-keys".urlPercentEncoding(), value: Swift.String(maxKeys).urlPercentEncoding())
            items.append(maxKeysQueryItem)
        }
        if let keyMarker = keyMarker {
            let keyMarkerQueryItem = ClientRuntime.URLQueryItem(name: "key-marker".urlPercentEncoding(), value: Swift.String(keyMarker).urlPercentEncoding())
            items.append(keyMarkerQueryItem)
        }
        return items
    }
}
