// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetServerCertificateOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetServerCertificateOutput(serverCertificate: \(String(describing: serverCertificate)))"}
}
