// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Specifies the inventory configuration for an Amazon S3 bucket. For more information, see
///             <a href="https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETInventoryConfig.html">GET Bucket inventory</a> in the <i>Amazon S3 API Reference</i>.
///       </p>
public struct InventoryConfiguration: Equatable {
    /// <p>Contains information about where to publish the inventory results.</p>
    public let destination: InventoryDestination?
    /// <p>Specifies an inventory filter. The inventory only includes objects that meet the
    ///          filter's criteria.</p>
    public let filter: InventoryFilter?
    /// <p>The ID used to identify the inventory configuration.</p>
    public let id: String?
    /// <p>Object versions to include in the inventory list. If set to <code>All</code>, the list
    ///          includes all the object versions, which adds the version-related fields
    ///             <code>VersionId</code>, <code>IsLatest</code>, and <code>DeleteMarker</code> to the
    ///          list. If set to <code>Current</code>, the list does not contain these version-related
    ///          fields.</p>
    public let includedObjectVersions: InventoryIncludedObjectVersions?
    /// <p>Specifies whether the inventory is enabled or disabled. If set to <code>True</code>, an
    ///          inventory list is generated. If set to <code>False</code>, no inventory list is
    ///          generated.</p>
    public let isEnabled: Bool
    /// <p>Contains the optional fields that are included in the inventory results.</p>
    public let optionalFields: [InventoryOptionalField]?
    /// <p>Specifies the schedule for generating inventory results.</p>
    public let schedule: InventorySchedule?

    public init (
        destination: InventoryDestination? = nil,
        filter: InventoryFilter? = nil,
        id: String? = nil,
        includedObjectVersions: InventoryIncludedObjectVersions? = nil,
        isEnabled: Bool = false,
        optionalFields: [InventoryOptionalField]? = nil,
        schedule: InventorySchedule? = nil
    )
    {
        self.destination = destination
        self.filter = filter
        self.id = id
        self.includedObjectVersions = includedObjectVersions
        self.isEnabled = isEnabled
        self.optionalFields = optionalFields
        self.schedule = schedule
    }
}
