// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct PutBucketReplicationInputBodyMiddleware: Middleware {
    public let id: String = "PutBucketReplicationInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<PutBucketReplicationInput>,
                  next: H) -> Swift.Result<OperationOutput<PutBucketReplicationOutput>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        if let replicationConfiguration = input.operationInput.replicationConfiguration {
            do {
                let encoder = context.getEncoder()
                let data = try encoder.encode(replicationConfiguration)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            } catch let err {
                return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
            }
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<PutBucketReplicationInput>
    public typealias MOutput = OperationOutput<PutBucketReplicationOutput>
    public typealias Context = HttpContext
    public typealias MError = SdkError<PutBucketReplicationOutputError>
}
