// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension UploadPartCopyOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "UploadPartCopyOutput(bucketKeyEnabled: \(String(describing: bucketKeyEnabled)), copyPartResult: \(String(describing: copyPartResult)), copySourceVersionId: \(String(describing: copySourceVersionId)), requestCharged: \(String(describing: requestCharged)), sSECustomerAlgorithm: \(String(describing: sSECustomerAlgorithm)), sSECustomerKeyMD5: \(String(describing: sSECustomerKeyMD5)), sSEKMSKeyId: \(String(describing: sSEKMSKeyId)), serverSideEncryption: \(String(describing: serverSideEncryption)))"}
}
