// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateLogLevelsByResourceTypesInput: Equatable {
    /// <p>The log level for a log message.</p>
    public let defaultLogLevel: LogLevel?
    /// <p>The list of wireless device log options.</p>
    public let wirelessDeviceLogOptions: [WirelessDeviceLogOption]?
    /// <p>The list of wireless gateway log options.</p>
    public let wirelessGatewayLogOptions: [WirelessGatewayLogOption]?

    public init (
        defaultLogLevel: LogLevel? = nil,
        wirelessDeviceLogOptions: [WirelessDeviceLogOption]? = nil,
        wirelessGatewayLogOptions: [WirelessGatewayLogOption]? = nil
    )
    {
        self.defaultLogLevel = defaultLogLevel
        self.wirelessDeviceLogOptions = wirelessDeviceLogOptions
        self.wirelessGatewayLogOptions = wirelessGatewayLogOptions
    }
}

extension UpdateLogLevelsByResourceTypesInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "UpdateLogLevelsByResourceTypesInput(defaultLogLevel: \(String(describing: defaultLogLevel)), wirelessDeviceLogOptions: \(String(describing: wirelessDeviceLogOptions)), wirelessGatewayLogOptions: \(String(describing: wirelessGatewayLogOptions)))"}
}
