// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension NotifyApplicationStateInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "NotifyApplicationStateInput(applicationId: \(String(describing: applicationId)), dryRun: \(String(describing: dryRun)), status: \(String(describing: status)), updateDateTime: \(String(describing: updateDateTime)))"}
}
