// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension UpdateIncidentRecordInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "UpdateIncidentRecordInput(arn: \(String(describing: arn)), chatChannel: \(String(describing: chatChannel)), clientToken: \(String(describing: clientToken)), impact: \(String(describing: impact)), notificationTargets: \(String(describing: notificationTargets)), status: \(String(describing: status)), summary: \(String(describing: summary)), title: \(String(describing: title)))"}
}
