// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>
///             Request structure to request all available bundles.
///         </p>
public struct ListBundlesInput: Equatable {
    /// <p>
    ///             Maximum number of records to list in a single response.
    ///         </p>
    public let maxResults: Int
    /// <p>
    ///             Pagination token. Set to null to start listing bundles from start.
    ///             If non-null pagination token is returned in a result, then pass its
    ///             value in here in another request to list more bundles.
    ///         </p>
    public let nextToken: String?

    public init (
        maxResults: Int = 0,
        nextToken: String? = nil
    )
    {
        self.maxResults = maxResults
        self.nextToken = nextToken
    }
}

extension ListBundlesInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ListBundlesInput(maxResults: \(String(describing: maxResults)), nextToken: \(String(describing: nextToken)))"}
}
