//
// Copyright Amazon.com Inc. or its affiliates.
// All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by smithy-swift-codegen. DO NOT EDIT!

import Foundation
import protocol ClientRuntime.PaginateToken
import struct ClientRuntime.PaginatorSequence

extension BillingClient {
    /// Paginate over `[GetCreditAllocationHistoryOutput]` results.
    ///
    /// When this operation is called, an `AsyncSequence` is created. AsyncSequences are lazy so no service
    /// calls are made until the sequence is iterated over. This also means there is no guarantee that the request is valid
    /// until then. If there are errors in your request, you will see the failures only after you start iterating.
    /// - Parameters:
    ///     - input: A `[GetCreditAllocationHistoryInput]` to start pagination
    /// - Returns: An `AsyncSequence` that can iterate over `GetCreditAllocationHistoryOutput`
    public func getCreditAllocationHistoryPaginated(input: GetCreditAllocationHistoryInput) -> ClientRuntime.PaginatorSequence<GetCreditAllocationHistoryInput, GetCreditAllocationHistoryOutput> {
        return ClientRuntime.PaginatorSequence<GetCreditAllocationHistoryInput, GetCreditAllocationHistoryOutput>(input: input, inputKey: \.nextToken, outputKey: \.nextToken, paginationFunction: self.getCreditAllocationHistory(input:))
    }
}

extension GetCreditAllocationHistoryInput: ClientRuntime.PaginateToken {
    public func usingPaginationToken(_ token: Swift.String) -> GetCreditAllocationHistoryInput {
        return GetCreditAllocationHistoryInput(
            accountId: self.accountId,
            creditId: self.creditId,
            endDate: self.endDate,
            maxResults: self.maxResults,
            nextToken: token,
            startDate: self.startDate
        )}
}

extension PaginatorSequence where OperationStackInput == GetCreditAllocationHistoryInput, OperationStackOutput == GetCreditAllocationHistoryOutput {
    /// This paginator transforms the `AsyncSequence` returned by `getCreditAllocationHistoryPaginated`
    /// to access the nested member `[BillingClientTypes.CreditAllocationHistoryEntry]`
    /// - Returns: `[BillingClientTypes.CreditAllocationHistoryEntry]`
    public func creditAllocationHistoryList() async throws -> [BillingClientTypes.CreditAllocationHistoryEntry] {
        return try await self.asyncCompactMap { item in item.creditAllocationHistoryList }
    }
}
extension BillingClient {
    /// Paginate over `[ListBillingViewsOutput]` results.
    ///
    /// When this operation is called, an `AsyncSequence` is created. AsyncSequences are lazy so no service
    /// calls are made until the sequence is iterated over. This also means there is no guarantee that the request is valid
    /// until then. If there are errors in your request, you will see the failures only after you start iterating.
    /// - Parameters:
    ///     - input: A `[ListBillingViewsInput]` to start pagination
    /// - Returns: An `AsyncSequence` that can iterate over `ListBillingViewsOutput`
    public func listBillingViewsPaginated(input: ListBillingViewsInput) -> ClientRuntime.PaginatorSequence<ListBillingViewsInput, ListBillingViewsOutput> {
        return ClientRuntime.PaginatorSequence<ListBillingViewsInput, ListBillingViewsOutput>(input: input, inputKey: \.nextToken, outputKey: \.nextToken, paginationFunction: self.listBillingViews(input:))
    }
}

extension ListBillingViewsInput: ClientRuntime.PaginateToken {
    public func usingPaginationToken(_ token: Swift.String) -> ListBillingViewsInput {
        return ListBillingViewsInput(
            activeTimeRange: self.activeTimeRange,
            arns: self.arns,
            billingViewTypes: self.billingViewTypes,
            maxResults: self.maxResults,
            names: self.names,
            nextToken: token,
            ownerAccountId: self.ownerAccountId,
            sourceAccountId: self.sourceAccountId
        )}
}

extension PaginatorSequence where OperationStackInput == ListBillingViewsInput, OperationStackOutput == ListBillingViewsOutput {
    /// This paginator transforms the `AsyncSequence` returned by `listBillingViewsPaginated`
    /// to access the nested member `[BillingClientTypes.BillingViewListElement]`
    /// - Returns: `[BillingClientTypes.BillingViewListElement]`
    public func billingViews() async throws -> [BillingClientTypes.BillingViewListElement] {
        return try await self.asyncCompactMap { item in item.billingViews }
    }
}
extension BillingClient {
    /// Paginate over `[ListEnterpriseSupportLinkedAccountChargesOutput]` results.
    ///
    /// When this operation is called, an `AsyncSequence` is created. AsyncSequences are lazy so no service
    /// calls are made until the sequence is iterated over. This also means there is no guarantee that the request is valid
    /// until then. If there are errors in your request, you will see the failures only after you start iterating.
    /// - Parameters:
    ///     - input: A `[ListEnterpriseSupportLinkedAccountChargesInput]` to start pagination
    /// - Returns: An `AsyncSequence` that can iterate over `ListEnterpriseSupportLinkedAccountChargesOutput`
    public func listEnterpriseSupportLinkedAccountChargesPaginated(input: ListEnterpriseSupportLinkedAccountChargesInput) -> ClientRuntime.PaginatorSequence<ListEnterpriseSupportLinkedAccountChargesInput, ListEnterpriseSupportLinkedAccountChargesOutput> {
        return ClientRuntime.PaginatorSequence<ListEnterpriseSupportLinkedAccountChargesInput, ListEnterpriseSupportLinkedAccountChargesOutput>(input: input, inputKey: \.nextToken, outputKey: \.nextToken, paginationFunction: self.listEnterpriseSupportLinkedAccountCharges(input:))
    }
}

extension ListEnterpriseSupportLinkedAccountChargesInput: ClientRuntime.PaginateToken {
    public func usingPaginationToken(_ token: Swift.String) -> ListEnterpriseSupportLinkedAccountChargesInput {
        return ListEnterpriseSupportLinkedAccountChargesInput(
            accountId: self.accountId,
            billingMonth: self.billingMonth,
            maxResults: self.maxResults,
            nextToken: token
        )}
}

extension PaginatorSequence where OperationStackInput == ListEnterpriseSupportLinkedAccountChargesInput, OperationStackOutput == ListEnterpriseSupportLinkedAccountChargesOutput {
    /// This paginator transforms the `AsyncSequence` returned by `listEnterpriseSupportLinkedAccountChargesPaginated`
    /// to access the nested member `[BillingClientTypes.LinkedAccountCharge]`
    /// - Returns: `[BillingClientTypes.LinkedAccountCharge]`
    public func linkedAccount() async throws -> [BillingClientTypes.LinkedAccountCharge] {
        return try await self.asyncCompactMap { item in item.linkedAccount }
    }
}
extension BillingClient {
    /// Paginate over `[ListSourceViewsForBillingViewOutput]` results.
    ///
    /// When this operation is called, an `AsyncSequence` is created. AsyncSequences are lazy so no service
    /// calls are made until the sequence is iterated over. This also means there is no guarantee that the request is valid
    /// until then. If there are errors in your request, you will see the failures only after you start iterating.
    /// - Parameters:
    ///     - input: A `[ListSourceViewsForBillingViewInput]` to start pagination
    /// - Returns: An `AsyncSequence` that can iterate over `ListSourceViewsForBillingViewOutput`
    public func listSourceViewsForBillingViewPaginated(input: ListSourceViewsForBillingViewInput) -> ClientRuntime.PaginatorSequence<ListSourceViewsForBillingViewInput, ListSourceViewsForBillingViewOutput> {
        return ClientRuntime.PaginatorSequence<ListSourceViewsForBillingViewInput, ListSourceViewsForBillingViewOutput>(input: input, inputKey: \.nextToken, outputKey: \.nextToken, paginationFunction: self.listSourceViewsForBillingView(input:))
    }
}

extension ListSourceViewsForBillingViewInput: ClientRuntime.PaginateToken {
    public func usingPaginationToken(_ token: Swift.String) -> ListSourceViewsForBillingViewInput {
        return ListSourceViewsForBillingViewInput(
            arn: self.arn,
            maxResults: self.maxResults,
            nextToken: token
        )}
}

extension PaginatorSequence where OperationStackInput == ListSourceViewsForBillingViewInput, OperationStackOutput == ListSourceViewsForBillingViewOutput {
    /// This paginator transforms the `AsyncSequence` returned by `listSourceViewsForBillingViewPaginated`
    /// to access the nested member `[Swift.String]`
    /// - Returns: `[Swift.String]`
    public func sourceViews() async throws -> [Swift.String] {
        return try await self.asyncCompactMap { item in item.sourceViews }
    }
}
