// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetTemplateInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetTemplateInput(changeSetName: \(String(describing: changeSetName)), stackName: \(String(describing: stackName)), templateStage: \(String(describing: templateStage)))"}
}
