// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Represents the output of a <code>CreateCacheParameterGroup</code> operation.</p>
public struct CacheParameterGroup: Equatable {
    /// <p>The ARN (Amazon Resource Name) of the cache parameter group.</p>
    public let aRN: String?
    /// <p>The name of the cache parameter group family that this cache parameter group is compatible with.</p>
    ///         <p>Valid values are:
    ///     <code>memcached1.4</code> |
    ///      <code>memcached1.5</code> |
    ///       <code>memcached1.6</code> |
    ///     <code>redis2.6</code> |
    ///     <code>redis2.8</code> |
    ///     <code>redis3.2</code> |
    ///     <code>redis4.0</code> |
    ///      <code>redis5.0</code> |
    ///       <code>redis6.x</code> |
    ///     </p>
    public let cacheParameterGroupFamily: String?
    /// <p>The name of the cache parameter group.</p>
    public let cacheParameterGroupName: String?
    /// <p>The description for this cache parameter group.</p>
    public let description: String?
    /// <p>Indicates whether the parameter group is associated with a Global datastore</p>
    public let isGlobal: Bool

    public init (
        aRN: String? = nil,
        cacheParameterGroupFamily: String? = nil,
        cacheParameterGroupName: String? = nil,
        description: String? = nil,
        isGlobal: Bool = false
    )
    {
        self.aRN = aRN
        self.cacheParameterGroupFamily = cacheParameterGroupFamily
        self.cacheParameterGroupName = cacheParameterGroupName
        self.description = description
        self.isGlobal = isGlobal
    }
}

extension CacheParameterGroup: CustomDebugStringConvertible {
    public var debugDescription: String {
        "CacheParameterGroup(aRN: \(String(describing: aRN)), cacheParameterGroupFamily: \(String(describing: cacheParameterGroupFamily)), cacheParameterGroupName: \(String(describing: cacheParameterGroupName)), description: \(String(describing: description)), isGlobal: \(String(describing: isGlobal)))"}
}
