// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CreateUserGroupInputHeadersMiddleware: Middleware {
    public let id: String = "CreateUserGroupInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateUserGroupInput>,
                  next: H) -> Swift.Result<OperationOutput<CreateUserGroupOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateUserGroupInput>
    public typealias MOutput = OperationOutput<CreateUserGroupOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CreateUserGroupOutputError>
}

public struct CreateUserGroupInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateUserGroupInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateUserGroupInput>,
                  next: H) -> Swift.Result<OperationOutput<CreateUserGroupOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateUserGroupInput>
    public typealias MOutput = OperationOutput<CreateUserGroupOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CreateUserGroupOutputError>
}

public struct CreateUserGroupInputBodyMiddleware: Middleware {
    public let id: String = "CreateUserGroupInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateUserGroupInput>,
                  next: H) -> Swift.Result<OperationOutput<CreateUserGroupOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            let encoder = context.getEncoder()
            let data = try encoder.encode(input.operationInput)
            let body = HttpBody.data(data)
            input.builder.withBody(body)
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateUserGroupInput>
    public typealias MOutput = OperationOutput<CreateUserGroupOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CreateUserGroupOutputError>
}

extension CreateUserGroupInput: Encodable, Reflection {
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Key.self)
        if let engine = engine {
            try container.encode(engine, forKey: Key("Engine"))
        }
        if let tags = tags {
            var tagsContainer = container.nestedContainer(keyedBy: Key.self, forKey: Key("Tags"))
            for (index0, tag0) in tags.enumerated() {
                try tagsContainer.encode(tag0, forKey: Key("Tag.\(index0.advanced(by: 1))"))
            }
        }
        if let userGroupId = userGroupId {
            try container.encode(userGroupId, forKey: Key("UserGroupId"))
        }
        if let userIds = userIds {
            var userIdsContainer = container.nestedContainer(keyedBy: Key.self, forKey: Key("UserIds"))
            for (index0, userid0) in userIds.enumerated() {
                try userIdsContainer.encode(userid0, forKey: Key("member.\(index0.advanced(by: 1))"))
            }
        }
        try container.encode("CreateUserGroup", forKey:Key("Action"))
        try container.encode("2015-02-02", forKey:Key("Version"))
    }
}
