// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Describes the pending maintenance actions for a resource.</p>
public struct ResourcePendingMaintenanceActions: Equatable {
    /// <p>A list that provides details about the pending maintenance actions for the
    ///       resource.</p>
    public let pendingMaintenanceActionDetails: [PendingMaintenanceAction]?
    /// <p>The ARN of the resource that has pending maintenance actions.</p>
    public let resourceIdentifier: String?

    public init (
        pendingMaintenanceActionDetails: [PendingMaintenanceAction]? = nil,
        resourceIdentifier: String? = nil
    )
    {
        self.pendingMaintenanceActionDetails = pendingMaintenanceActionDetails
        self.resourceIdentifier = resourceIdentifier
    }
}
