// Code generated by smithy-swift-codegen. DO NOT EDIT!



public enum UserImportJobStatusType {
    case created
    case expired
    case failed
    case inprogress
    case pending
    case stopped
    case stopping
    case succeeded
    case sdkUnknown(String)
}

extension UserImportJobStatusType : Equatable, RawRepresentable, Codable, CaseIterable, Hashable {
    public static var allCases: [UserImportJobStatusType] {
        return [
            .created,
            .expired,
            .failed,
            .inprogress,
            .pending,
            .stopped,
            .stopping,
            .succeeded,
            .sdkUnknown("")
        ]
    }
    public init?(rawValue: String) {
        let value = Self.allCases.first(where: { $0.rawValue == rawValue })
        self = value ?? Self.sdkUnknown(rawValue)
    }
    public var rawValue: String {
        switch self {
        case .created: return "Created"
        case .expired: return "Expired"
        case .failed: return "Failed"
        case .inprogress: return "InProgress"
        case .pending: return "Pending"
        case .stopped: return "Stopped"
        case .stopping: return "Stopping"
        case .succeeded: return "Succeeded"
        case let .sdkUnknown(s): return s
        }
    }
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(RawValue.self)
        self = UserImportJobStatusType(rawValue: rawValue) ?? UserImportJobStatusType.sdkUnknown(rawValue)
    }
}
