// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListActionsInputBody: Equatable {
}

extension ListActionsInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
