// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct SetIdentityPoolConfigurationInputQueryItemMiddleware: Middleware {
    public let id: String = "SetIdentityPoolConfigurationInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<SetIdentityPoolConfigurationInput>,
                  next: H) -> Swift.Result<OperationOutput<SetIdentityPoolConfigurationOutput>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<SetIdentityPoolConfigurationInput>
    public typealias MOutput = OperationOutput<SetIdentityPoolConfigurationOutput>
    public typealias Context = HttpContext
    public typealias MError = SdkError<SetIdentityPoolConfigurationOutputError>
}
