// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ModifyWorkspaceAccessPropertiesOutputResponse: Equatable {

    public init() {}
}

extension ModifyWorkspaceAccessPropertiesOutputResponse: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ModifyWorkspaceAccessPropertiesOutputResponse()"}
}
