// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CreateContactListInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateContactListInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateContactListInput>,
                  next: H) -> Swift.Result<OperationOutput<CreateContactListOutput>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateContactListInput>
    public typealias MOutput = OperationOutput<CreateContactListOutput>
    public typealias Context = HttpContext
    public typealias MError = SdkError<CreateContactListOutputError>
}
