// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SavingsPlansUtilizationDetail: CustomDebugStringConvertible {
    public var debugDescription: String {
        "SavingsPlansUtilizationDetail(amortizedCommitment: \(String(describing: amortizedCommitment)), attributes: \(String(describing: attributes)), savings: \(String(describing: savings)), savingsPlanArn: \(String(describing: savingsPlanArn)), utilization: \(String(describing: utilization)))"}
}
