// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CreateHttpNamespaceInputQueryItemMiddleware: Middleware {
    public let id: String = "CreateHttpNamespaceInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CreateHttpNamespaceInput>,
                  next: H) -> Swift.Result<OperationOutput<CreateHttpNamespaceOutput>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CreateHttpNamespaceInput>
    public typealias MOutput = OperationOutput<CreateHttpNamespaceOutput>
    public typealias Context = HttpContext
    public typealias MError = SdkError<CreateHttpNamespaceOutputError>
}
