// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct PutConfigurationSetDeliveryOptionsOutputResponseBody: Equatable {
}

extension PutConfigurationSetDeliveryOptionsOutputResponseBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
