// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListDatasetsOutputBody: Equatable {
    public let datasets: [DatasetSummary]?
    public let nextToken: String?
}

extension ListDatasetsOutputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case datasets
        case nextToken
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let datasetsContainer = try containerValues.decodeIfPresent([DatasetSummary].self, forKey: .datasets)
        var datasetsDecoded0:[DatasetSummary]? = nil
        if let datasetsContainer = datasetsContainer {
            datasetsDecoded0 = [DatasetSummary]()
            for structure0 in datasetsContainer {
                datasetsDecoded0?.append(structure0)
            }
        }
        datasets = datasetsDecoded0
        let nextTokenDecoded = try containerValues.decodeIfPresent(String.self, forKey: .nextToken)
        nextToken = nextTokenDecoded
    }
}
