// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension PostContentInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "PostContentInput(accept: \(String(describing: accept)), activeContexts: \(String(describing: activeContexts)), botAlias: \(String(describing: botAlias)), botName: \(String(describing: botName)), contentType: \(String(describing: contentType)), inputStream: \(String(describing: inputStream)), requestAttributes: \(String(describing: requestAttributes)), sessionAttributes: \(String(describing: sessionAttributes)), userId: \(String(describing: userId)))"}
}
