// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct GetWorkflowExecutionHistoryInputHeadersMiddleware: Middleware {
    public let id: String = "GetWorkflowExecutionHistoryInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetWorkflowExecutionHistoryInput>,
                  next: H) -> Swift.Result<OperationOutput<GetWorkflowExecutionHistoryOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetWorkflowExecutionHistoryInput>
    public typealias MOutput = OperationOutput<GetWorkflowExecutionHistoryOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<GetWorkflowExecutionHistoryOutputError>
}

public struct GetWorkflowExecutionHistoryInputQueryItemMiddleware: Middleware {
    public let id: String = "GetWorkflowExecutionHistoryInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetWorkflowExecutionHistoryInput>,
                  next: H) -> Swift.Result<OperationOutput<GetWorkflowExecutionHistoryOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetWorkflowExecutionHistoryInput>
    public typealias MOutput = OperationOutput<GetWorkflowExecutionHistoryOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<GetWorkflowExecutionHistoryOutputError>
}

public struct GetWorkflowExecutionHistoryInputBodyMiddleware: Middleware {
    public let id: String = "GetWorkflowExecutionHistoryInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<GetWorkflowExecutionHistoryInput>,
                  next: H) -> Swift.Result<OperationOutput<GetWorkflowExecutionHistoryOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            if try !input.operationInput.allPropertiesAreNull() {
                let encoder = context.getEncoder()
                let data = try encoder.encode(input.operationInput)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            }
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<GetWorkflowExecutionHistoryInput>
    public typealias MOutput = OperationOutput<GetWorkflowExecutionHistoryOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<GetWorkflowExecutionHistoryOutputError>
}

extension GetWorkflowExecutionHistoryInput: Encodable, Reflection {
    enum CodingKeys: String, CodingKey {
        case domain
        case execution
        case maximumPageSize
        case nextPageToken
        case reverseOrder
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let domain = domain {
            try encodeContainer.encode(domain, forKey: .domain)
        }
        if let execution = execution {
            try encodeContainer.encode(execution, forKey: .execution)
        }
        if maximumPageSize != 0 {
            try encodeContainer.encode(maximumPageSize, forKey: .maximumPageSize)
        }
        if let nextPageToken = nextPageToken {
            try encodeContainer.encode(nextPageToken, forKey: .nextPageToken)
        }
        if reverseOrder != false {
            try encodeContainer.encode(reverseOrder, forKey: .reverseOrder)
        }
    }
}
