// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetMilestoneInputBody: Equatable {
}

extension GetMilestoneInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
