// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Represents the output for <code>ListStreams</code>.</p>
public struct ListStreamsOutput: Equatable {
    /// <p>If set to <code>true</code>, there are more streams available to list.</p>
    public let hasMoreStreams: Bool?
    /// <p>The names of the streams that are associated with the AWS account making the
    ///                 <code>ListStreams</code> request.</p>
    public let streamNames: [String]?

    public init (
        hasMoreStreams: Bool? = nil,
        streamNames: [String]? = nil
    )
    {
        self.hasMoreStreams = hasMoreStreams
        self.streamNames = streamNames
    }
}
