// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ListShardsOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ListShardsOutput(nextToken: \(String(describing: nextToken)), shards: \(String(describing: shards)))"}
}
