// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension HistoricalMetric: CustomDebugStringConvertible {
    public var debugDescription: String {
        "HistoricalMetric(name: \(String(describing: name)), statistic: \(String(describing: statistic)), threshold: \(String(describing: threshold)), unit: \(String(describing: unit)))"}
}
