// Code generated by smithy-swift-codegen. DO NOT EDIT!



public enum DeleteFleetErrorCode {
    case fleetIdDoesNotExist
    case fleetIdMalformed
    case fleetNotInDeletableState
    case unexpectedError
    case sdkUnknown(String)
}

extension DeleteFleetErrorCode : Equatable, RawRepresentable, Codable, CaseIterable, Hashable {
    public static var allCases: [DeleteFleetErrorCode] {
        return [
            .fleetIdDoesNotExist,
            .fleetIdMalformed,
            .fleetNotInDeletableState,
            .unexpectedError,
            .sdkUnknown("")
        ]
    }
    public init?(rawValue: String) {
        let value = Self.allCases.first(where: { $0.rawValue == rawValue })
        self = value ?? Self.sdkUnknown(rawValue)
    }
    public var rawValue: String {
        switch self {
        case .fleetIdDoesNotExist: return "fleetIdDoesNotExist"
        case .fleetIdMalformed: return "fleetIdMalformed"
        case .fleetNotInDeletableState: return "fleetNotInDeletableState"
        case .unexpectedError: return "unexpectedError"
        case let .sdkUnknown(s): return s
        }
    }
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(RawValue.self)
        self = DeleteFleetErrorCode(rawValue: rawValue) ?? DeleteFleetErrorCode.sdkUnknown(rawValue)
    }
}
