// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension EnableVolumeIOOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "EnableVolumeIOOutput()"}
}
