// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct StartExecutionOutputBody: Equatable {
    public let executionArn: String?
    public let startDate: Date?
}

extension StartExecutionOutputBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case executionArn
        case startDate
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let executionArnDecoded = try containerValues.decodeIfPresent(String.self, forKey: .executionArn)
        executionArn = executionArnDecoded
        let startDateDecoded = try containerValues.decodeIfPresent(Date.self, forKey: .startDate)
        startDate = startDateDecoded
    }
}
