// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetRegexPatternSetOutput: Equatable {
    /// <p>Information about the <a>RegexPatternSet</a> that you specified in the <code>GetRegexPatternSet</code> request, including the identifier of the pattern set and the regular expression patterns you want AWS WAF to search for. </p>
    public let regexPatternSet: RegexPatternSet?

    public init (
        regexPatternSet: RegexPatternSet? = nil
    )
    {
        self.regexPatternSet = regexPatternSet
    }
}
