// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GetSampledRequestsOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "GetSampledRequestsOutput(populationSize: \(String(describing: populationSize)), sampledRequests: \(String(describing: sampledRequests)), timeWindow: \(String(describing: timeWindow)))"}
}
