// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CancelTaskExecutionInputHeadersMiddleware: Middleware {
    public let id: String = "CancelTaskExecutionInputHeadersMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelTaskExecutionInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelTaskExecutionOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelTaskExecutionInput>
    public typealias MOutput = OperationOutput<CancelTaskExecutionOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelTaskExecutionOutputError>
}

public struct CancelTaskExecutionInputQueryItemMiddleware: Middleware {
    public let id: String = "CancelTaskExecutionInputQueryItemMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelTaskExecutionInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelTaskExecutionOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelTaskExecutionInput>
    public typealias MOutput = OperationOutput<CancelTaskExecutionOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelTaskExecutionOutputError>
}

public struct CancelTaskExecutionInputBodyMiddleware: Middleware {
    public let id: String = "CancelTaskExecutionInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: SerializeStepInput<CancelTaskExecutionInput>,
                  next: H) -> Swift.Result<OperationOutput<CancelTaskExecutionOutputResponse>, MError>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context,
    Self.MError == H.MiddlewareError
    {
        do {
            if try !input.operationInput.allPropertiesAreNull() {
                let encoder = context.getEncoder()
                let data = try encoder.encode(input.operationInput)
                let body = HttpBody.data(data)
                input.builder.withBody(body)
            }
        } catch let err {
            return .failure(.client(ClientError.serializationFailed(err.localizedDescription)))
        }
        return next.handle(context: context, input: input)
    }

    public typealias MInput = SerializeStepInput<CancelTaskExecutionInput>
    public typealias MOutput = OperationOutput<CancelTaskExecutionOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
    public typealias MError = SdkError<CancelTaskExecutionOutputError>
}

extension CancelTaskExecutionInput: Encodable, Reflection {
    enum CodingKeys: String, CodingKey {
        case taskExecutionArn = "TaskExecutionArn"
    }

    public func encode(to encoder: Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let taskExecutionArn = taskExecutionArn {
            try encodeContainer.encode(taskExecutionArn, forKey: .taskExecutionArn)
        }
    }
}
