// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeTaskExecutionInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeTaskExecutionInput(taskExecutionArn: \(String(describing: taskExecutionArn)))"}
}
