// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// Amazon Web Services AppFabric quickly connects software as a service (SaaS) applications across your organization. This allows IT and security teams to easily manage and secure applications using a standard schema, and employees can complete everyday tasks faster using generative artificial intelligence (AI). You can use these APIs to complete AppFabric tasks, such as setting up audit log ingestions or viewing user access. For more information about AppFabric, including the required permissions to use the service, see the [Amazon Web Services AppFabric Administration Guide](https://docs.aws.amazon.com/appfabric/latest/adminguide/). For more information about using the Command Line Interface (CLI) to manage your AppFabric resources, see the [AppFabric section of the CLI Reference](https://docs.aws.amazon.com/cli/latest/reference/appfabric/index.html).
public protocol AppFabricClientProtocol {
    /// Gets user access details in a batch request. This action polls data from the tasks that are kicked off by the StartUserAccessTasks action.
    ///
    /// - Parameter BatchGetUserAccessTasksInput : [no documentation found]
    ///
    /// - Returns: `BatchGetUserAccessTasksOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func batchGetUserAccessTasks(input: BatchGetUserAccessTasksInput) async throws -> BatchGetUserAccessTasksOutput
    /// Establishes a connection between Amazon Web Services AppFabric and an application, which allows AppFabric to call the APIs of the application.
    ///
    /// - Parameter ConnectAppAuthorizationInput : [no documentation found]
    ///
    /// - Returns: `ConnectAppAuthorizationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func connectAppAuthorization(input: ConnectAppAuthorizationInput) async throws -> ConnectAppAuthorizationOutput
    /// Creates an app authorization within an app bundle, which allows AppFabric to connect to an application.
    ///
    /// - Parameter CreateAppAuthorizationInput : [no documentation found]
    ///
    /// - Returns: `CreateAppAuthorizationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ServiceQuotaExceededException` : The request exceeds a service quota.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func createAppAuthorization(input: CreateAppAuthorizationInput) async throws -> CreateAppAuthorizationOutput
    /// Creates an app bundle to collect data from an application using AppFabric.
    ///
    /// - Parameter CreateAppBundleInput : [no documentation found]
    ///
    /// - Returns: `CreateAppBundleOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ServiceQuotaExceededException` : The request exceeds a service quota.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func createAppBundle(input: CreateAppBundleInput) async throws -> CreateAppBundleOutput
    /// Creates a data ingestion for an application.
    ///
    /// - Parameter CreateIngestionInput : [no documentation found]
    ///
    /// - Returns: `CreateIngestionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ServiceQuotaExceededException` : The request exceeds a service quota.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func createIngestion(input: CreateIngestionInput) async throws -> CreateIngestionOutput
    /// Creates an ingestion destination, which specifies how an application's ingested data is processed by Amazon Web Services AppFabric and where it's delivered.
    ///
    /// - Parameter CreateIngestionDestinationInput : [no documentation found]
    ///
    /// - Returns: `CreateIngestionDestinationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ServiceQuotaExceededException` : The request exceeds a service quota.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func createIngestionDestination(input: CreateIngestionDestinationInput) async throws -> CreateIngestionDestinationOutput
    /// Deletes an app authorization. You must delete the associated ingestion before you can delete an app authorization.
    ///
    /// - Parameter DeleteAppAuthorizationInput : [no documentation found]
    ///
    /// - Returns: `DeleteAppAuthorizationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func deleteAppAuthorization(input: DeleteAppAuthorizationInput) async throws -> DeleteAppAuthorizationOutput
    /// Deletes an app bundle. You must delete all associated app authorizations before you can delete an app bundle.
    ///
    /// - Parameter DeleteAppBundleInput : [no documentation found]
    ///
    /// - Returns: `DeleteAppBundleOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func deleteAppBundle(input: DeleteAppBundleInput) async throws -> DeleteAppBundleOutput
    /// Deletes an ingestion. You must stop (disable) the ingestion and you must delete all associated ingestion destinations before you can delete an app ingestion.
    ///
    /// - Parameter DeleteIngestionInput : [no documentation found]
    ///
    /// - Returns: `DeleteIngestionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func deleteIngestion(input: DeleteIngestionInput) async throws -> DeleteIngestionOutput
    /// Deletes an ingestion destination. This deletes the association between an ingestion and it's destination. It doesn't delete previously ingested data or the storage destination, such as the Amazon S3 bucket where the data is delivered. If the ingestion destination is deleted while the associated ingestion is enabled, the ingestion will fail and is eventually disabled.
    ///
    /// - Parameter DeleteIngestionDestinationInput : [no documentation found]
    ///
    /// - Returns: `DeleteIngestionDestinationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func deleteIngestionDestination(input: DeleteIngestionDestinationInput) async throws -> DeleteIngestionDestinationOutput
    /// Returns information about an app authorization.
    ///
    /// - Parameter GetAppAuthorizationInput : [no documentation found]
    ///
    /// - Returns: `GetAppAuthorizationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func getAppAuthorization(input: GetAppAuthorizationInput) async throws -> GetAppAuthorizationOutput
    /// Returns information about an app bundle.
    ///
    /// - Parameter GetAppBundleInput : [no documentation found]
    ///
    /// - Returns: `GetAppBundleOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func getAppBundle(input: GetAppBundleInput) async throws -> GetAppBundleOutput
    /// Returns information about an ingestion.
    ///
    /// - Parameter GetIngestionInput : [no documentation found]
    ///
    /// - Returns: `GetIngestionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func getIngestion(input: GetIngestionInput) async throws -> GetIngestionOutput
    /// Returns information about an ingestion destination.
    ///
    /// - Parameter GetIngestionDestinationInput : [no documentation found]
    ///
    /// - Returns: `GetIngestionDestinationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func getIngestionDestination(input: GetIngestionDestinationInput) async throws -> GetIngestionDestinationOutput
    /// Returns a list of all app authorizations configured for an app bundle.
    ///
    /// - Parameter ListAppAuthorizationsInput : [no documentation found]
    ///
    /// - Returns: `ListAppAuthorizationsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func listAppAuthorizations(input: ListAppAuthorizationsInput) async throws -> ListAppAuthorizationsOutput
    /// Returns a list of app bundles.
    ///
    /// - Parameter ListAppBundlesInput : [no documentation found]
    ///
    /// - Returns: `ListAppBundlesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func listAppBundles(input: ListAppBundlesInput) async throws -> ListAppBundlesOutput
    /// Returns a list of all ingestion destinations configured for an ingestion.
    ///
    /// - Parameter ListIngestionDestinationsInput : [no documentation found]
    ///
    /// - Returns: `ListIngestionDestinationsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func listIngestionDestinations(input: ListIngestionDestinationsInput) async throws -> ListIngestionDestinationsOutput
    /// Returns a list of all ingestions configured for an app bundle.
    ///
    /// - Parameter ListIngestionsInput : [no documentation found]
    ///
    /// - Returns: `ListIngestionsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func listIngestions(input: ListIngestionsInput) async throws -> ListIngestionsOutput
    /// Returns a list of tags for a resource.
    ///
    /// - Parameter ListTagsForResourceInput : [no documentation found]
    ///
    /// - Returns: `ListTagsForResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func listTagsForResource(input: ListTagsForResourceInput) async throws -> ListTagsForResourceOutput
    /// Starts (enables) an ingestion, which collects data from an application.
    ///
    /// - Parameter StartIngestionInput : [no documentation found]
    ///
    /// - Returns: `StartIngestionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func startIngestion(input: StartIngestionInput) async throws -> StartIngestionOutput
    /// Starts the tasks to search user access status for a specific email address. The tasks are stopped when the user access status data is found. The tasks are terminated when the API calls to the application time out.
    ///
    /// - Parameter StartUserAccessTasksInput : [no documentation found]
    ///
    /// - Returns: `StartUserAccessTasksOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func startUserAccessTasks(input: StartUserAccessTasksInput) async throws -> StartUserAccessTasksOutput
    /// Stops (disables) an ingestion.
    ///
    /// - Parameter StopIngestionInput : [no documentation found]
    ///
    /// - Returns: `StopIngestionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func stopIngestion(input: StopIngestionInput) async throws -> StopIngestionOutput
    /// Assigns one or more tags (key-value pairs) to the specified resource.
    ///
    /// - Parameter TagResourceInput : [no documentation found]
    ///
    /// - Returns: `TagResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func tagResource(input: TagResourceInput) async throws -> TagResourceOutput
    /// Removes a tag or tags from a resource.
    ///
    /// - Parameter UntagResourceInput : [no documentation found]
    ///
    /// - Returns: `UntagResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func untagResource(input: UntagResourceInput) async throws -> UntagResourceOutput
    /// Updates an app authorization within an app bundle, which allows AppFabric to connect to an application. If the app authorization was in a connected state, updating the app authorization will set it back to a PendingConnect state.
    ///
    /// - Parameter UpdateAppAuthorizationInput : [no documentation found]
    ///
    /// - Returns: `UpdateAppAuthorizationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func updateAppAuthorization(input: UpdateAppAuthorizationInput) async throws -> UpdateAppAuthorizationOutput
    /// Updates an ingestion destination, which specifies how an application's ingested data is processed by Amazon Web Services AppFabric and where it's delivered.
    ///
    /// - Parameter UpdateIngestionDestinationInput : [no documentation found]
    ///
    /// - Returns: `UpdateIngestionDestinationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : You are not authorized to perform this operation.
    /// - `ConflictException` : The request has created a conflict. Check the request parameters and try again.
    /// - `InternalServerException` : The request processing has failed because of an unknown error, exception, or failure with an internal server.
    /// - `ResourceNotFoundException` : The specified resource does not exist.
    /// - `ServiceQuotaExceededException` : The request exceeds a service quota.
    /// - `ThrottlingException` : The request rate exceeds the limit.
    /// - `ValidationException` : The request has invalid or missing parameters.
    func updateIngestionDestination(input: UpdateIngestionDestinationInput) async throws -> UpdateIngestionDestinationOutput
}

public enum AppFabricClientTypes {}
