// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Represents a unique message ID.</p>
public struct SendBounceOutput: Equatable {
    /// <p>The message ID of the bounce message.</p>
    public let messageId: String?

    public init (
        messageId: String? = nil
    )
    {
        self.messageId = messageId
    }
}
