// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Represents a request to enable or disable Amazon SES Easy DKIM signing for an identity. For
///             more information about setting up Easy DKIM, see the <a href="https://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim.html">Amazon SES Developer Guide</a>.</p>
public struct SetIdentityDkimEnabledInput: Equatable {
    /// <p>Sets whether DKIM signing is enabled for an identity. Set to <code>true</code> to
    ///             enable DKIM signing for this identity; <code>false</code> to disable it. </p>
    public let dkimEnabled: Bool
    /// <p>The identity for which DKIM signing should be enabled or disabled.</p>
    public let identity: String?

    public init (
        dkimEnabled: Bool = false,
        identity: String? = nil
    )
    {
        self.dkimEnabled = dkimEnabled
        self.identity = identity
    }
}
