// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeVirtualRouterOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeVirtualRouterOutput(virtualRouter: \(String(describing: virtualRouter)))"}
}
