// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RequestError: CustomDebugStringConvertible {
    public var debugDescription: String {
        "RequestError(message: \(String(describing: message)), turkErrorCode: \(String(describing: turkErrorCode)))"}
}
