// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetFacetOutputResponseBody: Equatable {
    public let facet: Facet?
}

extension GetFacetOutputResponseBody: Decodable {
    enum CodingKeys: String, CodingKey {
        case facet = "Facet"
    }

    public init (from decoder: Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let facetDecoded = try containerValues.decodeIfPresent(Facet.self, forKey: .facet)
        facet = facetDecoded
    }
}
