// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DeleteReportDefinitionInputBody: Equatable {
}

extension DeleteReportDefinitionInputBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
