// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SetQueueAttributesInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "SetQueueAttributesInput(attributes: \(String(describing: attributes)), queueUrl: \(String(describing: queueUrl)))"}
}
