// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension AggregateConformancePackComplianceSummary: CustomDebugStringConvertible {
    public var debugDescription: String {
        "AggregateConformancePackComplianceSummary(complianceSummary: \(String(describing: complianceSummary)), groupName: \(String(describing: groupName)))"}
}
