// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SavingsPlanOfferingProperty: CustomDebugStringConvertible {
    public var debugDescription: String {
        "SavingsPlanOfferingProperty(name: \(String(describing: name)), value: \(String(describing: value)))"}
}
