// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension S3ApplicationCodeLocationDescription: CustomDebugStringConvertible {
    public var debugDescription: String {
        "S3ApplicationCodeLocationDescription(bucketARN: \(String(describing: bucketARN)), fileKey: \(String(describing: fileKey)), objectVersion: \(String(describing: objectVersion)))"}
}
