// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeWorkforceInput: Equatable {
    /// <p>The name of the private workforce whose access you want to restrict.
    ///                 <code>WorkforceName</code> is automatically set to <code>default</code> when a
    ///             workforce is created and cannot be modified. </p>
    public let workforceName: String?

    public init (
        workforceName: String? = nil
    )
    {
        self.workforceName = workforceName
    }
}

extension DescribeWorkforceInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeWorkforceInput(workforceName: \(String(describing: workforceName)))"}
}
