// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension TrialComponentSummary: CustomDebugStringConvertible {
    public var debugDescription: String {
        "TrialComponentSummary(createdBy: \(String(describing: createdBy)), creationTime: \(String(describing: creationTime)), displayName: \(String(describing: displayName)), endTime: \(String(describing: endTime)), lastModifiedBy: \(String(describing: lastModifiedBy)), lastModifiedTime: \(String(describing: lastModifiedTime)), startTime: \(String(describing: startTime)), status: \(String(describing: status)), trialComponentArn: \(String(describing: trialComponentArn)), trialComponentName: \(String(describing: trialComponentName)), trialComponentSource: \(String(describing: trialComponentSource)))"}
}
