// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// The AWS Single Sign-On (SSO) Identity Store service provides a single place to retrieve all of your identities (users and groups). For more information about AWS, see the [AWS Single Sign-On User Guide](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html).
public protocol IdentitystoreClientProtocol {
    /// Retrieves the group metadata and attributes from GroupId in an identity store.
    func describeGroup(input: DescribeGroupInput) async throws -> DescribeGroupOutputResponse
    /// Retrieves the user metadata and attributes from UserId in an identity store.
    func describeUser(input: DescribeUserInput) async throws -> DescribeUserOutputResponse
    /// Lists the attribute name and value of the group that you specified in the search. We only support DisplayName as a valid filter attribute path currently, and filter is required. This API returns minimum attributes, including GroupId and group DisplayName in the response.
    func listGroups(input: ListGroupsInput) async throws -> ListGroupsOutputResponse
    /// Lists the attribute name and value of the user that you specified in the search. We only support UserName as a valid filter attribute path currently, and filter is required. This API returns minimum attributes, including UserId and UserName in the response.
    func listUsers(input: ListUsersInput) async throws -> ListUsersOutputResponse
}

public enum IdentitystoreClientTypes {}
