// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct OptInPhoneNumberOutputResponseBody: Equatable {
}

extension OptInPhoneNumberOutputResponseBody: Decodable {

    public init (from decoder: Decoder) throws {
    }
}
