// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ListForecastExportJobsInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "ListForecastExportJobsInput(filters: \(String(describing: filters)), maxResults: \(String(describing: maxResults)), nextToken: \(String(describing: nextToken)))"}
}
