// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Archive Cdn Settings
public struct ArchiveCdnSettings: Equatable {
    /// Archive S3 Settings
    public let archiveS3Settings: ArchiveS3Settings?

    public init (
        archiveS3Settings: ArchiveS3Settings? = nil
    )
    {
        self.archiveS3Settings = archiveS3Settings
    }
}
