// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Audio Normalization Algorithm
public enum AudioNormalizationAlgorithm {
    case itu17701
    case itu17702
    case sdkUnknown(String)
}

extension AudioNormalizationAlgorithm : Equatable, RawRepresentable, Codable, CaseIterable, Hashable {
    public static var allCases: [AudioNormalizationAlgorithm] {
        return [
            .itu17701,
            .itu17702,
            .sdkUnknown("")
        ]
    }
    public init?(rawValue: String) {
        let value = Self.allCases.first(where: { $0.rawValue == rawValue })
        self = value ?? Self.sdkUnknown(rawValue)
    }
    public var rawValue: String {
        switch self {
        case .itu17701: return "ITU_1770_1"
        case .itu17702: return "ITU_1770_2"
        case let .sdkUnknown(s): return s
        }
    }
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(RawValue.self)
        self = AudioNormalizationAlgorithm(rawValue: rawValue) ?? AudioNormalizationAlgorithm.sdkUnknown(rawValue)
    }
}
