// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension StopChannelInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "StopChannelInput(channelId: \(String(describing: channelId)))"}
}
