// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension TransferInputDeviceInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "TransferInputDeviceInput(inputDeviceId: \(String(describing: inputDeviceId)), targetCustomerId: \(String(describing: targetCustomerId)), targetRegion: \(String(describing: targetRegion)), transferMessage: \(String(describing: transferMessage)))"}
}
