// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeUserProfileInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeUserProfileInput(userArn: \(String(describing: userArn)))"}
}
