// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct PutLexiconInput: Equatable {
    /// <p>Content of the PLS lexicon as string data.</p>
    public let content: String?
    /// <p>Name of the lexicon. The name must follow the regular express format [0-9A-Za-z]{1,20}.
    ///       That is, the name is a case-sensitive alphanumeric string up to 20 characters long. </p>
    public let name: String?

    public init (
        content: String? = nil,
        name: String? = nil
    )
    {
        self.content = content
        self.name = name
    }
}

extension PutLexiconInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "PutLexiconInput(content: \(String(describing: content)), name: \(String(describing: name)))"}
}
