// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// <p>Represents the input for a request operation.</p>
public struct CreateFleetLocationsInput: Equatable {
    /// <p>A unique identifier for the fleet to add locations to. You can use either the fleet ID or ARN value.</p>
    public let fleetId: String?
    /// <p>A list of locations to deploy additional instances to and manage as part of the fleet.
    ///             You can add any GameLift-supported AWS Region as a remote location, in the form of an AWS
    ///             Region code such as <code>us-west-2</code>. </p>
    public let locations: [LocationConfiguration]?

    public init (
        fleetId: String? = nil,
        locations: [LocationConfiguration]? = nil
    )
    {
        self.fleetId = fleetId
        self.locations = locations
    }
}
