// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateNumberOfDomainControllersInput: Equatable {
    /// <p>The number of domain controllers desired in the directory.</p>
    public let desiredNumber: Int
    /// <p>Identifier of the directory to which the domain controllers will be added or removed.</p>
    public let directoryId: String?

    public init (
        desiredNumber: Int = 0,
        directoryId: String? = nil
    )
    {
        self.desiredNumber = desiredNumber
        self.directoryId = directoryId
    }
}
