name: Generate Docs

on:
  push:
    branches:
        - 'generatedocs/**'
  pull_request:
    branches:
        - 'generatedocs/**'
  workflow_dispatch:

env:
  BUILDER_VERSION: v0.8.19
  BUILDER_SOURCE: releases
  # host owned by CRT team to host aws-crt-builder releases. Contact their on-call with any issues
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-sdk-swift
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  AWS_SDK_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift
  AWS_CRT_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/aws-crt-swift
  SMITHY_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/smithy-swift

# This release script is work in progress.  We will need to update the script to
# * Ensure that unit tests pass for all targets prior to generating a release
# * Create release based on one of the platform's built results
# * Add Readme.md file in release folder
# * Pin to versions of aws-crt-swift and smithy-swift
#

jobs:
  macos-release:
    runs-on: macos-11
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install swift-doc
        run: brew install swiftdocorg/formulae/swift-doc
      - name: Build and Test ${{ env.PACKAGE_NAME }}
        run: |
          python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder.pyz')"
          chmod a+x builder.pyz
          AWS_CRT_SWIFT_CI_DIR="${{ env.AWS_CRT_SWIFT_CI_DIR }}" AWS_SDK_SWIFT_CI_DIR="${{ env.AWS_SDK_SWIFT_CI_DIR }}" SMITHY_SWIFT_CI_DIR="${{ env.SMITHY_SWIFT_CI_DIR }}" ./builder.pyz build -p ${{ env.PACKAGE_NAME }}
          ./gradlew -p codegen/sdk-codegen build
          ./gradlew -p codegen/sdk-codegen stageSdks
          ./scripts/mergeModels.sh release
          ./scripts/generatePackageSwift.swift > Package.swift
          cat Package.swift
          ./scripts/generateDocs.sh release reference/0.x
          ./scripts/generateIndexPage.sh reference/0.x
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reference/0.x
          destination_dir: reference/0.x
          allow_empty_commit: false # optional, default is false
          user_name: AWS CI
          user_email: nobody@amazonaws.com
          commit_message: Update docs
          disable_nojekyll: true
