name: Swift6 Compatibility

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  AWS_SWIFT_SDK_USE_LOCAL_DEPS: 1

jobs:
  bump-swift-tools-version:
    if: github.repository == 'awslabs/aws-sdk-swift' || github.event_name == 'pull_request'
    runs-on: macos-15-xlarge
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
      - name: Checkout aws-sdk-swift
        uses: actions/checkout@v4
        with:
          path: aws-sdk-swift
      - name: Checkout smithy-swift with composite action
        uses: ./aws-sdk-swift/.github/actions/checkout-smithy-swift-composite-action
        with:
          AUTOMATION_USER_SSH_PRIVATE_KEY: ${{ secrets.AUTOMATION_USER_SSH_PRIVATE_KEY }}
          STAGING_PARTNER_REPO: ${{ secrets.STAGING_PARTNER_REPO }}
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: 2-${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            2-${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
            2-${{ runner.os }}-gradle-
      - name: Cache Swift
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/.cache/org.swift.swiftpm
          key: 1-${{ runner.os }}-${{ matrix.xcode }}-${{ hashFiles('Package.swift', 'AWSSDKSwiftCLI/Package.swift') }}
          restore-keys: |
            1-${{ runner.os }}-${{ matrix.xcode }}-${{ hashFiles('Package.swift', 'AWSSDKSwiftCLI/Package.swift') }}
            1-${{ runner.os }}-${{ matrix.xcode }}-
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Tools Versions
        run: ./aws-sdk-swift/scripts/ci_steps/log_tool_versions.sh
      - name: Code-Generate SDK
        run: |
          cd aws-sdk-swift
          ./scripts/ci_steps/codegen_sdk.sh
      - name: Build on swift-tools-version 6.0
        run: |
          set -euo pipefail
          cd aws-sdk-swift
          perl -pi -e 's{^// swift-tools-version:\d+\.\d+}{// swift-tools-version:6.0}' Package.swift
          swift build
