name: TempReleaseDebugging

on:
  push:
    branches:
        - 'releaseJob/**'
  pull_request:
    branches:
        - 'releaseJob/**'
  workflow_dispatch:

env:
  BUILDER_VERSION: v0.8.19
  BUILDER_SOURCE: releases
  # host owned by CRT team to host aws-crt-builder releases. Contact their on-call with any issues
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-sdk-swift
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  AWS_SDK_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift
  AWS_CRT_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/aws-crt-swift
  SMITHY_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/smithy-swift

jobs:
  macos-release:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.app
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build and Test ${{ env.PACKAGE_NAME }}
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        run: |
          mkdir -p release/Dynamo
          echo "somecontents" > release/Dynamo/SomeFile.txt
          echo "//This is part of the release" >> Package.swift
          cat Package.swift
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "release_version"
          pr_title: "release test"
          pr_body: "automated release*"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_reviewer: "wooj2"
          pr_assignee: "wooj2"
          pr_label: "auto-pr"
          pr_milestone: "" 
          pr_draft: true
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}