// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct BatchGetImageInput: Equatable {
    /// <p>The accepted media types for the request.</p>
    ///         <p>Valid values: <code>application/vnd.docker.distribution.manifest.v1+json</code> |
    ///                 <code>application/vnd.docker.distribution.manifest.v2+json</code> |
    ///                 <code>application/vnd.oci.image.manifest.v1+json</code>
    ///          </p>
    public let acceptedMediaTypes: [String]?
    /// <p>A list of image ID references that correspond to images to describe. The format of the
    ///                 <code>imageIds</code> reference is <code>imageTag=tag</code> or
    ///                 <code>imageDigest=digest</code>.</p>
    public let imageIds: [ImageIdentifier]?
    /// <p>The AWS account ID associated with the registry that contains the images to describe.
    ///             If you do not specify a registry, the default registry is assumed.</p>
    public let registryId: String?
    /// <p>The repository that contains the images to describe.</p>
    public let repositoryName: String?

    public init (
        acceptedMediaTypes: [String]? = nil,
        imageIds: [ImageIdentifier]? = nil,
        registryId: String? = nil,
        repositoryName: String? = nil
    )
    {
        self.acceptedMediaTypes = acceptedMediaTypes
        self.imageIds = imageIds
        self.registryId = registryId
        self.repositoryName = repositoryName
    }
}

extension BatchGetImageInput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "BatchGetImageInput(acceptedMediaTypes: \(String(describing: acceptedMediaTypes)), imageIds: \(String(describing: imageIds)), registryId: \(String(describing: registryId)), repositoryName: \(String(describing: repositoryName)))"}
}
