// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct StartImageScanInput: Equatable {
    /// <p>An object with identifying information for an Amazon ECR image.</p>
    public let imageId: ImageIdentifier?
    /// <p>The AWS account ID associated with the registry that contains the repository in
    ///             which to start an image scan request. If you do not specify a registry, the default registry is assumed.</p>
    public let registryId: String?
    /// <p>The name of the repository that contains the images to scan.</p>
    public let repositoryName: String?

    public init (
        imageId: ImageIdentifier? = nil,
        registryId: String? = nil,
        repositoryName: String? = nil
    )
    {
        self.imageId = imageId
        self.registryId = registryId
        self.repositoryName = repositoryName
    }
}
