// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DescribeAccountAssignmentCreationStatusOutput: CustomDebugStringConvertible {
    public var debugDescription: String {
        "DescribeAccountAssignmentCreationStatusOutput(accountAssignmentCreationStatus: \(String(describing: accountAssignmentCreationStatus)))"}
}
